
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T08:24:48.677-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "VoidService",
                      portName = "VoidPort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Void/v1.1",
                      wsdlLocation = "Void.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy.VoidPortType")
                      
public class VoidPortTypeImpl implements VoidPortType {

    private static final Logger LOG = Logger.getLogger(VoidPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy.VoidPortType#processVoid(com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy.VoidShipmentRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy.VoidShipmentResponse processVoid(VoidShipmentRequest body,UPSSecurity upsSecurity) throws VoidErrorMessage    { 
        LOG.info("Executing operation processVoid");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.voidws.proxy.VoidShipmentResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new VoidErrorMessage("VoidErrorMessage...");
    }

}
