
package com.meritconinc.shiplinx.ws.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-29T13:56:07.409-04:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "RatingErrors", targetNamespace = "http://www.proxy.ws.shiplinx.meritconinc.com/datatypes")
public class RatingException extends Exception {
    
    private com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType ratingErrors;

    public RatingException() {
        super();
    } 
    
    public RatingException(String message) {
        super(message);
    }
    
    public RatingException(String message, Throwable cause) {
        super(message, cause);
    }

    public RatingException(String message, com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType ratingErrors) {
        super(message);
        this.ratingErrors = ratingErrors;
    }

    public RatingException(String message, com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType ratingErrors, Throwable cause) {
        super(message, cause);
        this.ratingErrors = ratingErrors;
    }

    public com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType getFaultInfo() {
        return this.ratingErrors;
    }
}
