
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.ws.proxy;

import java.util.logging.Logger;

import com.meritconinc.shiplinx.ws.ShiplinxWebServiceAdaptor;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-29T13:56:07.424-04:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "RatingService",
                      portName = "RatingServiceImplPort",
                      targetNamespace = "http://www.proxy.ws.shiplinx.meritconinc.com/",
                      wsdlLocation = "ws/RatingService.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.ws.proxy.RatingPortType")
                      
public class RatingPortTypeImpl implements RatingPortType { 

    private static final Logger LOG = Logger.getLogger(RatingPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.ws.proxy.RatingPortType#rateShipment(com.meritconinc.shiplinx.ws.proxy.ratingrequest.RatingRequestWSType  body ,)com.meritconinc.shiplinx.ws.proxy.datatypes.SecurityWSType  security )*
     */
    public com.meritconinc.shiplinx.ws.proxy.ratingresponse.RatingResponseWSType rateShipment(com.meritconinc.shiplinx.ws.proxy.ratingrequest.RatingRequestWSType body,com.meritconinc.shiplinx.ws.proxy.datatypes.SecurityWSType security) throws RatingException    { 
        LOG.info("Executing operation rateShipment");
        try {
        	ShiplinxWebServiceAdaptor adaptor = new ShiplinxWebServiceAdaptor();
        	return adaptor.rateShipment(body, security);
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RatingException("RatingException...");
    }

}
