package com.meritconinc.shiplinx.ws.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-29T13:56:07.455-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "RatingService", 
                  wsdlLocation = "RatingService.wsdl",
                  targetNamespace = "http://www.proxy.ws.shiplinx.meritconinc.com/") 
public class RatingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.proxy.ws.shiplinx.meritconinc.com/", "RatingService");
    public final static QName RatingServiceImplPort = new QName("http://www.proxy.ws.shiplinx.meritconinc.com/", "RatingServiceImplPort");
    static {
        URL url = RatingService.class.getResource("RatingService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(RatingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "RatingService.wsdl");
        }        
        WSDL_LOCATION = url;
    }

    public RatingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RatingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RatingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RatingPortType
     */
    @WebEndpoint(name = "RatingServiceImplPort")
    public RatingPortType getRatingServiceImplPort() {
        return super.getPort(RatingServiceImplPort, RatingPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RatingPortType
     */
    @WebEndpoint(name = "RatingServiceImplPort")
    public RatingPortType getRatingServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RatingServiceImplPort, RatingPortType.class, features);
    }

}
