
package com.meritconinc.shiplinx.ws.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-29T13:56:07.440-04:00
 * Generated source version: 2.5.2
 * 
 */
 
public class RatingPortType_RatingServiceImplPort_Server{

    protected RatingPortType_RatingServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new RatingPortTypeImpl();
        String address = "https://localhost:8443/shiplinx/services/RatingService";
        Endpoint.publish(address, implementor);
    } 
    
    public static void main(String args[]) throws java.lang.Exception { 
        new RatingPortType_RatingServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
