
package com.meritconinc.shiplinx.ws.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-06T21:55:32.940-05:00
 * Generated source version: 2.5.2
 * 
 */
public final class ShippingPortType_ShippingServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.proxy.ws.shiplinx.meritconinc.com/", "ShippingService");

    private ShippingPortType_ShippingServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShippingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                } 
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShippingService ss = new ShippingService(wsdlURL, SERVICE_NAME);
        ShippingPortType port = ss.getShippingServiceImplPort();  
        
        {
        System.out.println("Invoking getOrderInfo...");
        long _getOrderInfo_body = 0;
        com.meritconinc.shiplinx.ws.proxy.datatypes.SecurityWSType _getOrderInfo_security = null;
        try {
            com.meritconinc.shiplinx.ws.proxy.shippingresponse.ShippingResponseWSType _getOrderInfo__return = port.getOrderInfo(_getOrderInfo_body, _getOrderInfo_security);
            System.out.println("getOrderInfo.result=" + _getOrderInfo__return);

        } catch (GetOrderInfoException e) { 
            System.out.println("Expected exception: GetOrderInfoException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking shipOrder...");
        com.meritconinc.shiplinx.ws.proxy.shippingrequest.ShippingRequestWSType _shipOrder_body = null;
        com.meritconinc.shiplinx.ws.proxy.datatypes.SecurityWSType _shipOrder_security = null;
        try {
            com.meritconinc.shiplinx.ws.proxy.shippingresponse.ShippingResponseWSType _shipOrder__return = port.shipOrder(_shipOrder_body, _shipOrder_security);
            System.out.println("shipOrder.result=" + _shipOrder__return);

        } catch (ShippingException e) { 
            System.out.println("Expected exception: ShippingException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
