
package com.meritconinc.shiplinx.ws.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-06T21:55:32.987-05:00
 * Generated source version: 2.5.2
 * 
 */
 
public class ShippingPortType_ShippingServiceImplPort_Server{

    protected ShippingPortType_ShippingServiceImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ShippingPortTypeImpl();
        String address = "https://localhost:8443/shiplinx/services/ShippingService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ShippingPortType_ShippingServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    } 
}
