package com.meritconinc.shiplinx.carrier.purolator.ws.serviceavailability.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * Service Contract Class - ServiceAvailabilityServiceContract
 *
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-27T20:30:28.608-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://purolator.com/pws/service/v1", name = "ServiceAvailabilityServiceContract")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServiceAvailabilityServiceContract {

    /**
     * ValidateCityPostalCodeZip
     * @param request ValidateCityPostalCodeZipRequest
     * @return ValidateCityPostalCodeZipResponse
     */
    @WebResult(name = "ValidateCityPostalCodeZipResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "ValidateCityPostalCodeZipResponse")
    @Action(input = "http://purolator.com/pws/service/v1/ValidateCityPostalCodeZip", output = "http://purolator.com/pws/service/v1/ServiceAvailabilityServiceContract/ValidateCityPostalCodeZipResponse", fault = {@FaultAction(className = ServiceAvailabilityServiceContractValidateCityPostalCodeZipValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ServiceAvailabilityServiceContract/ValidateCityPostalCodeZipValidationFaultFault")})
    @WebMethod(operationName = "ValidateCityPostalCodeZip", action = "http://purolator.com/pws/service/v1/ValidateCityPostalCodeZip")
    public ValidateCityPostalCodeZipResponseContainer validateCityPostalCodeZip(
        @WebParam(partName = "ValidateCityPostalCodeZipRequest", name = "ValidateCityPostalCodeZipRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        ValidateCityPostalCodeZipRequestContainer validateCityPostalCodeZipRequest
    ) throws ServiceAvailabilityServiceContractValidateCityPostalCodeZipValidationFaultFaultFaultMessage;

    /**
     * GetServicesOptions
     * @param request GetServicesOptionsRequest
     * @return GetServicesOptionsResponse
     */
    @WebResult(name = "GetServicesOptionsResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetServicesOptionsResponse")
    @Action(input = "http://purolator.com/pws/service/v1/GetServicesOptions", output = "http://purolator.com/pws/service/v1/ServiceAvailabilityServiceContract/GetServicesOptionsResponse", fault = {@FaultAction(className = ServiceAvailabilityServiceContractGetServicesOptionsValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ServiceAvailabilityServiceContract/GetServicesOptionsValidationFaultFault")})
    @WebMethod(operationName = "GetServicesOptions", action = "http://purolator.com/pws/service/v1/GetServicesOptions")
    public GetServicesOptionsResponseContainer getServicesOptions(
        @WebParam(partName = "GetServicesOptionsRequest", name = "GetServicesOptionsRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        GetServicesOptionsRequestContainer getServicesOptionsRequest
    ) throws ServiceAvailabilityServiceContractGetServicesOptionsValidationFaultFaultFaultMessage;

    /**
     * GetServiceRules
     * @param request GetServiceRulesRequest
     * @return GetServiceRulesResponse
     */
    @WebResult(name = "GetServiceRulesResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetServiceRulesResponse")
    @Action(input = "http://purolator.com/pws/service/v1/GetServiceRules", output = "http://purolator.com/pws/service/v1/ServiceAvailabilityServiceContract/GetServiceRulesResponse", fault = {@FaultAction(className = ServiceAvailabilityServiceContractGetServiceRulesValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ServiceAvailabilityServiceContract/GetServiceRulesValidationFaultFault")})
    @WebMethod(operationName = "GetServiceRules", action = "http://purolator.com/pws/service/v1/GetServiceRules")
    public GetServiceRulesResponseContainer getServiceRules(
        @WebParam(partName = "GetServiceRulesRequest", name = "GetServiceRulesRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        GetServiceRulesRequestContainer getServiceRulesRequest
    ) throws ServiceAvailabilityServiceContractGetServiceRulesValidationFaultFaultFaultMessage;
}
