package com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:47:27.353-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "ReturnsManagementService", 
                  wsdlLocation = "ReturnsManagementService.wsdl",
                  targetNamespace = "http://purolator.com/pws/service/v1") 
public class ReturnsManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://purolator.com/pws/service/v1", "ReturnsManagementService");
    public final static QName ReturnsManagementServiceEndpoint = new QName("http://purolator.com/pws/service/v1", "ReturnsManagementServiceEndpoint");
    static {
        URL url = ReturnsManagementService.class.getResource("ReturnsManagementService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(ReturnsManagementService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "ReturnsManagementService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ReturnsManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReturnsManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReturnsManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ReturnShippingServiceContract
     */
    @WebEndpoint(name = "ReturnsManagementServiceEndpoint")
    public ReturnShippingServiceContract getReturnsManagementServiceEndpoint() {
        return super.getPort(ReturnsManagementServiceEndpoint, ReturnShippingServiceContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReturnShippingServiceContract
     */
    @WebEndpoint(name = "ReturnsManagementServiceEndpoint")
    public ReturnShippingServiceContract getReturnsManagementServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(ReturnsManagementServiceEndpoint, ReturnShippingServiceContract.class, features);
    }

}
