
package com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:47:27.317-04:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ValidationFault", targetNamespace = "http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")
public class ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage extends Exception {
    
    private com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.ValidationFault validationFault;

    public ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage() {
        super();
    }
    
    public ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage(String message, com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.ValidationFault validationFault) {
        super(message);
        this.validationFault = validationFault;
    }

    public ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage(String message, com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.ValidationFault validationFault, Throwable cause) {
        super(message, cause);
        this.validationFault = validationFault;
    }

    public com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.ValidationFault getFaultInfo() {
        return this.validationFault;
    }
}
