
package com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:47:27.283-04:00
 * Generated source version: 2.5.2
 * 
 */
public final class ReturnShippingServiceContract_ReturnsManagementServiceEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://purolator.com/pws/service/v1", "ReturnsManagementService");

    private ReturnShippingServiceContract_ReturnsManagementServiceEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReturnsManagementService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ReturnsManagementService ss = new ReturnsManagementService(wsdlURL, SERVICE_NAME);
        ReturnShippingServiceContract port = ss.getReturnsManagementServiceEndpoint();  
        
        {
        System.out.println("Invoking validateReturnsManagementShipment...");
        com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.ValidateReturnsManagementShipmentRequestContainer _validateReturnsManagementShipment_validateReturnsManagementShipmentRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.ValidateReturnsManagementShipmentResponseContainer _validateReturnsManagementShipment__return = port.validateReturnsManagementShipment(_validateReturnsManagementShipment_validateReturnsManagementShipmentRequest);
            System.out.println("validateReturnsManagementShipment.result=" + _validateReturnsManagementShipment__return);

        } catch (ReturnShippingServiceContractValidateReturnsManagementShipmentValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ReturnShippingServiceContract_ValidateReturnsManagementShipment_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createReturnsManagementShipment...");
        com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.CreateReturnsManagementShipmentRequestContainer _createReturnsManagementShipment_createReturnsManagementShipmentRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy.CreateReturnsManagementShipmentResponseContainer _createReturnsManagementShipment__return = port.createReturnsManagementShipment(_createReturnsManagementShipment_createReturnsManagementShipmentRequest);
            System.out.println("createReturnsManagementShipment.result=" + _createReturnsManagementShipment__return);

        } catch (ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: ReturnShippingServiceContract_CreateReturnsManagementShipment_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
