package com.meritconinc.shiplinx.carrier.purolator.ws.returnsmanagement.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * Service Contract Class - ReturnsManagementServiceContract
 *
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:47:27.339-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://purolator.com/pws/service/v1", name = "ReturnShippingServiceContract")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReturnShippingServiceContract {

    /**
     * ValidateReturnsManagementShipment
     * @param request ValidateReturnShipmentRequest
     * @return ValidateReturnShipmentResponse
     */
    @WebResult(name = "ValidateReturnsManagementShipmentResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "ValidateReturnsManagementShipmentResponse")
    @Action(input = "http://purolator.com/pws/service/v1/ValidateReturnShipment", output = "http://purolator.com/pws/service/v1/ReturnShippingServiceContract/ValidateReturnsManagementShipmentResponse", fault = {@FaultAction(className = ReturnShippingServiceContractValidateReturnsManagementShipmentValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ReturnShippingServiceContract/ValidateReturnsManagementShipmentValidationFaultFault")})
    @WebMethod(operationName = "ValidateReturnsManagementShipment", action = "http://purolator.com/pws/service/v1/ValidateReturnShipment")
    public ValidateReturnsManagementShipmentResponseContainer validateReturnsManagementShipment(
        @WebParam(partName = "ValidateReturnsManagementShipmentRequest", name = "ValidateReturnsManagementShipmentRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        ValidateReturnsManagementShipmentRequestContainer validateReturnsManagementShipmentRequest
    ) throws ReturnShippingServiceContractValidateReturnsManagementShipmentValidationFaultFaultFaultMessage;

    /**
     * CreateReturnsManagementShipment
     * @param request CreateReturnShipmentRequest
     * @return CreateReturnShipmentResponse
     */
    @WebResult(name = "CreateReturnsManagementShipmentResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "CreateReturnsManagementShipmentResponse")
    @Action(input = "http://purolator.com/pws/service/v1/CreateReturnShipment", output = "http://purolator.com/pws/service/v1/ReturnShippingServiceContract/CreateReturnsManagementShipmentResponse", fault = {@FaultAction(className = ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ReturnShippingServiceContract/CreateReturnsManagementShipmentValidationFaultFault")})
    @WebMethod(operationName = "CreateReturnsManagementShipment", action = "http://purolator.com/pws/service/v1/CreateReturnShipment")
    public CreateReturnsManagementShipmentResponseContainer createReturnsManagementShipment(
        @WebParam(partName = "CreateReturnsManagementShipmentRequest", name = "CreateReturnsManagementShipmentRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        CreateReturnsManagementShipmentRequestContainer createReturnsManagementShipmentRequest
    ) throws ReturnShippingServiceContractCreateReturnsManagementShipmentValidationFaultFaultFaultMessage;
}
