
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T21:34:08.981-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "FreightRateService",
                      portName = "FreightRatePort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightRate/v1.0",
                      wsdlLocation = "FreightRate.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy.FreightRatePortType")
                      
public class FreightRatePortTypeImpl implements FreightRatePortType {

    private static final Logger LOG = Logger.getLogger(FreightRatePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy.FreightRatePortType#processFreightRate(com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy.FreightRateRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy.FreightRateResponse processFreightRate(FreightRateRequest body,UPSSecurity upsSecurity) throws RateErrorMessage    { 
        LOG.info("Executing operation processFreightRate");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.freightrate.proxy.FreightRateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new RateErrorMessage("RateErrorMessage...");
    }

}
