package com.meritconinc.shiplinx.carrier.fedex;

public class FedExConstants { 
	/*public final static int SERVER_TRANSACTION_TYPE_FIELD_ID = 0 ;
	public final static int SERVER_TRANSACTION_ID_FIELD_ID = 1 ;
	public final static int SERVER_SHIPPER_COMPANY_FIELD_ID = 4 ;
	public final static int SERVER_SHIPPER_ADDRESS1_FIELD_ID = 5 ;
	public final static int SERVER_SHIPPER_ADDRESS2_FIELD_ID = 6 ;
	public final static int SERVER_SHIPPER_CITY_FIELD_ID = 7 ;
	public final static int SERVER_SHIPPER_STATE_PROVINCE_FIELD_ID = 8 ;
	public final static int SERVER_SHIPPER_POSTAL_CODE_FIELD_ID = 9 ;
	public final static int SERVER_SHIPPER_ACCOUNT_NUMBER_FIELD_ID = 10 ;
	public final static int SERVER_RECIPIENT_COMPANY_FIELD_ID = 11 ;
	public final static int SERVER_RECIPIENT_CONTACT_NAME_FIELD_ID = 12 ;
	public final static int SERVER_RECIPIENT_ADDRESS1_FIELD_ID = 13 ;
	public final static int SERVER_RECIPIENT_ADDRESS2_FIELD_ID = 14 ;
	public final static int SERVER_RECIPIENT_CITY_FIELD_ID = 15 ;
	public final static int SERVER_RECIPIENT_STATE_PROVINCE_FIELD_ID = 16 ;
	public final static int SERVER_RECIPIENT_POSTAL_CODE_FIELD_ID = 17 ;
	public final static int SERVER_RECIPIENT_PHONE_NUMBER_FIELD_ID = 18 ;
	public final static int SERVER_PAYOR_ACCOUNT_NUMBER_FIELD_ID = 20 ;
	public final static int SERVER_PAYMENT_CODE_FIELD_ID = 23 ;
	public final static int SERVER_REFERENCE_NOTES_FIELD_ID = 25 ;
	public final static int SERVER_DECLARED_VALUE_FIELD_ID = 26 ;
	public final static int SERVER_COD_FLAG_FIELD_ID = 27 ;
	public final static int SERVER_TRACKING_NUMBER_FIELD_ID = 29 ;
	public final static int SERVER_COMMODITY_DESCRIPTION_FIELD_ID = 79 ;
	public final static int END_OF_TRANSACTION_FIELD_ID = 99 ;
	public final static int SERVER_SHIPPER_CONTACT_NAME_FIELD_ID = 32 ;
	public final static int SERVER_RECIPIENT_COUNTRY_CODE_FIELD_ID = 50 ;
	public final static int SERVER_COD_AMOUNT_FIELD_ID = 53 ;
	public final static int SERVER_PACKAGE_HEIGHT_FIELD_ID = 57 ;
	public final static int SERVER_PACKAGE_WIDTH_FIELD_ID = 58 ;
	public final static int SERVER_PACKAGE_LENGTH_FIELD_ID = 59 ;
	public final static int SERVER_CURRENCY_TYPE_FIELD_ID = 68 ;
	public final static int SERVER_COUNTRY_OF_ULTIMATE_DESTINATION_FIELD_ID = 74 ;
	public final static int SERVER_WEIGHT_TYPE_FIELD_ID = 75 ;	
	public final static int SERVER_NUMBER_OF_PACKAGES_FIELD_ID = 116 ;
	public final static int SERVER_SHIPPER_COUNTRY_FIELD_ID = 117 ;
	public final static int SERVER_SHIPPER_PHONE_NUMBER_FIELD_ID = 183 ;
	public final static int SERVER_LABEL_FORMAT_VALUE_FIELD_ID = 187 ;
	public final static int SERVER_RESIDENTIAL_DELIVERY_FLAG_FIELD_ID = 440 ;
	public final static int SERVER_METER_NUMBER_FIELD_ID = 498 ;
	public final static int SERVER_RATE_CURRENCY_FIELD_ID = 1090 ;
	public final static int SERVER_INSIDE_DELIVERY_FLAG_FIELD_ID = 1121 ;
	public final static int SERVER_SENDERS_EMAIL_FIELD_ID = 1201 ;
	public final static int SERVER_RECIPIENTS_EMAIL_FIELD_ID = 1202 ;
	public final static int SERVER_SATURDAY_DELIVERY_FLAG_FIELD_ID = 1266 ;
	public final static int SERVER_PACKAGING_TYPE_FIELD_ID = 1273 ;
	public final static int SERVER_SERVICE_TYPE_FIELD_ID = 1274 ;
	public final static int SERVER_THERMAL_LABEL_INDICATOR_FIELD_ID = 1282 ;
	public final static int SERVER_HAZARDOUS_MATERIALS_FLAG_FIELD_ID = 1331 ;
	public final static int SERVER_SHIPPER_DELIVERY_NOTIFICATION_FLAG_FIELD_ID = 1553 ;
	public final static int SERVER_SHIPPER_SHIP_ALERT_FLAG_FIELD_ID = 1554 ;
	public final static int SERVER_RECIPIENT_DELIVERY_NOTIFICATION_FLAG_FIELD_ID = 1556 ;
	public final static int SERVER_RECIPIENT_SHIP_ALERT_FLAG_FIELD_ID = 1557 ;
	public final static int SERVER_PACKAGE_WEIGHT_FIELD_ID = 1670 ;
	public final static int SERVER_COD_COLLECTION_TYPE_FIELD_ID = 3000 ;
	
	public final static String END_OF_TRANSACTION_FIELD_VALUE = "" ;

	public final static int SERVER_TRACK_REQUEST_TRANSACTION_TYPE = 42;
	public final static int SERVER_GLOBAL_SHIP_REQUEST_TRANSACTION_TYPE = 20;
	
	public final static int API_TRANSACTION_TYPE_FIELD_TAG = 0;
	public final static int API_CUSTOMER_TRANSACTION_IDENTIFIER_FIELD_TAG = 1;	
	public final static int API_SENDER_COMPANY_FIELD_TAG = 4;
	public final static int API_SENDER_ADDRESS1_FIELD_TAG = 5;
	public final static int API_SENDER_ADDRESS2_FIELD_TAG = 6;
	public final static int API_SENDER_CITY_FIELD_TAG = 7;
	public final static int API_SENDER_STATE_FIELD_TAG = 8;
	public final static int API_SENDER_POSTAL_CODE_FIELD_TAG = 9;
	public final static int API_SENDER_FEDEX_ACCOUNT_NUMBER_FIELD_TAG = 10;
	public final static int API_RECIPIENT_COMPANY_FIELD_TAG = 11;
	public final static int API_RECIPIENT_CONTACT_NAME_FIELD_TAG = 12;
	public final static int API_RECIPIENT_ADDRESS1_FIELD_TAG = 13;
	public final static int API_RECIPIENT_ADDRESS2_FIELD_TAG = 14;
	public final static int API_RECIPIENT_CITY_FIELD_TAG = 15;
	public final static int API_RECIPIENT_STATE_FIELD_TAG = 16;
	public final static int API_RECIPIENT_POSTAL_CODE_FIELD_TAG = 17;
	public final static int API_RECIPIENT_PHONE_NUMBER_FIELD_TAG = 18;
	public final static int API_PAYOR_ACCOUNT_NUMBER_FIELD_TAG = 20;
	public final static int API_PAY_TYPE_FIELD_TAG = 23;
	public final static int API_SHIP_DATE_FIELD_TAG = 24;
	public final static int API_REFERENCE_INFORMATION_FIELD_TAG = 25;
	public final static int API_COD_FLAG_FIELD_TAG = 27;
	public final static int API_COD_RETURN_TRACKING_NUMBER_FIELD_TAG = 27;
	public final static int API_SENDER_CONTACT_NAME_FIELD_TAG = 32;
	public final static int API_RECIPIENT_COUNTRY_CODE_FIELD_TAG = 50;
	public final static int API_DIM_HEIGHT_FIELD_TAG = 57;
	public final static int API_DIM_WIDTH_FIELD_TAG = 58;
	public final static int API_DIM_LENGTH_FIELD_TAG = 59;
	public final static int API_DECLARED_VALUE_CURRENCY_TYPE_FIELD_TAG = 68;
	public final static int API_COUNTRY_OF_ULTIMATE_DESTINATION_FIELD_TAG = 74;
	public final static int API_WEIGHT_UNITS_FIELD_TAG = 75;
	public final static int COMMODITY_NUMBER_OF_PIECES_FIELD_TAG = 76;
	public final static int COMMODITY_DESCRIPTION_OF_CONTENTS_FIELD_TAG = 79;
	public final static int API_PACKAGE_TOTAL_FIELD_TAG = 116;
	public final static int API_SENDER_COUNTRY_CODE_FIELD_TAG = 117;
	public final static int API_SENDER_PHONE_NUMBER_FIELD_TAG = 183;
	public final static int API_DOCUMENT_FLAG_FIELD_TAG = 190;
	public final static int API_COD_RETURN_LABEL_BUFFER = 411;
	public final static int API_RESIDENTIAL_DELIVERY_FLAG_FIELD_TAG = 440;
	public final static int API_METER_NUMBER_FIELD_TAG = 498;
	public final static int API_DIM_UNITS_FIELD_TAG = 1116;
	public final static int API_PACKAGE_SEQUENCE_FIELD_TAG = 1117;
	public final static int API_FUTURE_DAY_SHIPMENT_FLAG_FIELD_TAG = 1119;
	public final static int API_INSIDE_DELIVERY_FLAG_FIELD_TAG = 1121;
	public final static int API_MASTER_TRACKING_NUMBER_FIELD_TAG = 1123;
	public final static int API_MASTER_FORM_ID_FIELD_TAG = 1124;
	public final static int API_HAL_FIELD_TAG = 1200;
	public final static int API_SENDER_EMAIL_ADDRESS_FIELD_TAG = 1201;
	public final static int API_RECIPIENT_EMAIL_ADDRESS_FIELD_TAG = 1202;
	public final static int API_HAL_ADDRESS_TAG = 44;
	public final static int API_HAL_CITY_TAG = 46;
	public final static int API_HAL_STATE_TAG = 47;
	public final static int API_HAL_POSTALCODE_TAG = 48;
	public final static int API_HAL_PHONENUMBER_TAG = 49;
	public final static int API_HAL_CONTACTNAME_TAG = 1265;
		
	public final static int API_COD_RETURN_PHONE_TAG = 1237;
	public final static int API_COD_RETURN_COMPANY_TAG = 1238;
	public final static int API_COD_RETURN_ADDRESS1_TAG = 1240;
	public final static int API_COD_RETURN_ADDRESS2_TAG = 1241;
	public final static int API_COD_RETURN_CITY_TAG = 1242;
	public final static int API_COD_RETURN_STATE_TAG = 1243;
	public final static int API_COD_RETURN_POSTALCODE_TAG = 1244;
	
	public final static int API_SATURDAY_DELIVERY_FLAG_FIELD_TAG = 1266;
	public final static int API_FEDEX_PACKAGING_TYPE_FIELD_TAG = 1273;
	public final static int API_FEDEX_SLAC_TYPE_FIELD_TAG = 1271;
	public final static int API_FEDEX_SERVICE_TYPE_FIELD_TAG = 1274;
	public final static int API_PURCHASE_ORDER_NUMBER_FIELD_TAG = 1300;
	public final static int API_DANGEROUS_GOODS_TYPE_FIELD_TAG = 1331;
	public final static int API_DROP_OFF_TYPE_FIELD_TAG = 1333;
	public final static int API_LABEL_TYPE_FIELD_TAG = 1368;
	public final static int API_LABEL_PRINTER_TYPE_FIELD_TAG = 1369;
	public final static int API_LABEL_MEDIA_TYPE_FIELD_TAG = 1370;
	public final static int API_TOTAL_SHIPMENT_WEIGHT_FIELD_TAG = 1400;
	public final static int API_TOTAL_PACKAGE_WEIGHT_FIELD_TAG = 1401; 
	public final static int API_COD_COLLECT_AMOUNT_FIELD_TAG = 1409;
	public final static int API_TOTAL_CUSTOMS_VALUE_FIELD_TAG = 1411;
	public final static int API_DECLARED_VALUE_FIELD_TAG = 1415;
	public final static int API_COD_CUSTOMER_ACCOUNT_FIELD_TAG = 1432;
	public final static int API_SHIPPER_DELIVERY_NOTIFICATION_FLAG_FIELD_TAG = 1553;
	public final static int API_SHIPPER_SHIP_ALERT_FLAG_FIELD_TAG = 1554;
	public final static int API_RECIPIENT_DELIVERY_NOTIFICATION_FLAG_FIELD_TAG = 1556;
	public final static int API_RECIPIENT_SHIP_ALERT_FLAG_FIELD_TAG = 1557;
	public final static int API_MASK_ACCOUNT_NUMBER_FIELD_TAG = 2975;
	public final static int API_SIGNATURE_OPTION_FIELD_TAG = 2399;
	public final static int API_COD_COLLECTION_TYPE_FIELD_TAG = 3000;
	public final static int API_PURCHASE_ORDER_FIELD_TAG = 3001;
	public final static int API_INVOICE_FIELD_TAG = 3002;
	public final static int API_HAZARDOUS_MATERIALS_FLAG_FIELD_TAG = 3015;
	public final static int API_CARRIER_CODE_FIELD_TAG = 3025; 
	public final static int API_RESIDENTIAL_PICKUP_FLAG_FIELD_TAG = 3231;
	public final static int API_SUBSCRIBER_CONTACT_NAME_FIELD_TAG = 4003;
	public final static int API_SUBSCRIBER_COMPANY_NAME_FIELD_TAG = 4007;
	public final static int API_SUBSCRIBER_ADDRESS_LINE1_FIELD_TAG = 4008;
	public final static int API_SUBSCRIBER_ADDRESS_LINE2_FIELD_TAG = 4009;
	public final static int API_SUBSCRIBER_CITY_NAME_FIELD_TAG = 4011;
	public final static int API_SUBSCRIBER_STATE_CODE_FIELD_TAG = 4012;
	public final static int API_SUBSCRIBER_POSTAL_CODE_FIELD_TAG = 4013;
	public final static int API_SUBSCRIBER_COUNTRY_CODE_FIELD_TAG = 4014;
	public final static int API_SUBSCRIBER_PHONE_NUMBER_FIELD_TAG = 4015;
	public final static int API_SUBSCRIBER_PAGER_NUMBER_FIELD_TAG = 4017;
	public final static int API_SUBSCRIBER_EMAIL_ADDRESS_FIELD_TAG = 4018;
	public final static int API_SUBSCRIBER_FAX_NUMBER_FIELD_TAG = 4022;
	public final static int API_TRACKING_NUMBER_FIELD_TAG = 1537 ;
	public final static int API_SED_NUMBER_AES_EXEMPTION_FIELD_TAG = 1358;*/

	public final static String WEIGHT_TYPE_VALUE_LBS = "LBS";
	public final static String WEIGHT_TYPE_VALUE_KGS = "KGS";
	public final static String DIM_TYPE_VALUE_INCHES = "I";
	public final static String CURRENCY_TYPE_VALUE_USD = "USD";
	public final static String CURRENCY_TYPE_VALUE_CAD = "CAD";
	public final static String API_WEIGHT_UNITS_LBS_VALUE = "LBS";
	public final static String API_GENERIC_YES_VALUE = "Y";
	public final static String API_COD_COLLECTION_TYPE_ANY_VALUE = "1";
	public final static String API_COD_COLLECTION_TYPE_GUARANTEED_FUNDS_VALUE = "2";
	public final static String API_COD_COLLECTION_TYPE_CURRENCY_VALUE = "3";
	public final static String API_DANGEROUS_GOODS_TYPE_ACCESSIBLE_VALUE = "A";
	public final static String API_DANGEROUS_GOODS_TYPE_INACCESSIBLE_VALUE = "I";
	public final static String API_DROP_OFF_TYPE_REGULAR_VALUE = "1"; 
	
	

	public final static int API_SHIP_A_PACKAGE_REQUEST_TRANSACTION_TYPE = 21;
	public final static int API_RATE_REQUEST_TRANSACTION_TYPE = 22;
	public final static int API_SUBSCRIPTION_REQUEST_TRANSACTION_TYPE = 211;
	
	public final static int API_TRANSACTION_ERROR_CODE = 2;
	public final static int API_TRANSACTION_ERROR_MSG = 3;
	
	public final static String API_FEDEX_PACKAGING_TYPE_FEDEX_LETTER_VALUE = "06";
	public final static String API_FEDEX_PACKAGING_TYPE_FEDEX_CUSTOMER_PACKAGING_VALUE = "01";
	public final static String API_FEDEX_PACKAGING_TYPE_FEDEX_PAK_VALUE = "02";
	
	public final static int API_DROPOFF_REGULAR_VALUE = 1;
	public final static int API_DROPOFF_COURIER_VALUE = 2;
	public final static int API_DROPOFF_DROPBOX_VALUE = 3;
	public final static int API_DROPOFF_BSE_VALUE 	  = 4;
	public final static int API_DROPOFF_STATION_VALUE = 5;
	
	public final static int API_PAY_TYPE_BILL_SENDER = 1;
	public final static int API_PAY_TYPE_BILL_RECIPIENT = 2;
	public final static int API_PAY_TYPE_BILL_THIRD_PARTY = 3;
	public final static int API_PAY_TYPE_BILL_CREDIT_CARD = 4;
	public final static int API_PAY_TYPE_BILL_RECIPIENT_GROUND = 5;
	
	/*public final static String API_SERVICE_TYPE_FEDEX_PRIORITY_VALUE = "01";
	public final static String API_SERVICE_TYPE_FEDEX_OVERNIGHT_VALUE = "06";
	public final static String API_SERVICE_TYPE_FEDEX_GROUND_VALUE = "92";
	public final static String API_SERVICE_TYPE_FEDEX_STANDARD_OVERNIGHT_VALUE = "05";
	public final static String API_SERVICE_TYPE_FEDEX_2ND_DAY_VALUE = "03";
	public final static String API_SERVICE_TYPE_FEDEX_EXPRESS_SAVER_VALUE = "20";
	public final static String API_SERVICE_TYPE_FEDEX_INTL_PRIORITY_FREIGHT_VALUE = "70";
	public final static String API_SERVICE_TYPE_FEDEX_INTL_ECONOMY_FREIGHT_VALUE = "86";
	public final static String API_SERVICE_TYPE_FEDEX_2DAY_FREIGHT_VALUE = "80";
	public final static String API_SERVICE_TYPE_FEDEX_3DAY_FREIGHT_VALUE = "83";*/
	
	public final static String API_CARRIER_CODE_EXPRESS_VALUE = "FDXE";
	public final static String API_CARRIER_CODE_GROUND_VALUE = "FDXG";
	
	/*public final static int API_LABEL_PRINTER_TYPE_LASER_VALUE = 1;
	public final static int API_LABEL_MEDIA_TYPE_VALUE_3 = 3;
	public final static int API_LABEL_MEDIA_TYPE_VALUE_4 = 4;
	public final static int API_LABEL_MEDIA_TYPE_VALUE_5 = 5;
	public final static int API_LABEL_MEDIA_TYPE_VALUE_6 = 6;
	public final static int API_LABEL_MEDIA_TYPE_VALUE_7 = 7;
	public final static int API_LABEL_MEDIA_TYPE_VALUE_PDF_8 = 8;

	public final static int API_LABEL_BUFFER_FIELD_TAG = 188;
	
	public final static int API_DUTIES_PAY_TYPE = 70;
	public final static int API_DUTIES_PAY_TYPE_VALUE = 3;
	public final static int API_DUTIES_PAY_TYPE_RECIPIENT_VALUE = 2;
	public final static int API_DUTIES_PAYER_ACCOUNT_NUMBER = 71;
	                                             */
	
	/*public static final int ADDITIONAL_HANDLING =	0;	
	public static final int APPOINTMENT_DELIVERY =  26;    
	public static final int BROKER_SELECT_OPTION =  0;    
	public static final int CANADIAN_DESTINATION = 0;     
	public static final int CLEARANCE_ENTRY_FEE =  0;     
	public static final int COD = 21;                     
	public static final int DANGEROUS_GOODS = 8;          
	public static final int DELIVERY_AREA =  0;           
	public static final int DELIVERY_SIGNATURE_OPTIONS = 0;
	public static final int EMAIL_LABEL =  0;             
	public static final int EUROPE_FIRST = 0;             
	public static final int EXPORT =0;                
	public static final int FEDEX_TAG =0;             
	public static final int FUEL = 31;                     
	public static final int HOME_DELIVERY_APPOINTMENT = 0;
	public static final int HOME_DELIVERY_DATE_CERTAIN =0;
	public static final int HOME_DELIVERY_EVENING =0;     
	public static final int INSIDE_DELIVERY = 25;          
	public static final int INSIDE_PICKUP = 0;            
	public static final int INSURED_VALUE = 0;            
	public static final int INTERHAWAII = 0;              
	public static final int NON_STANDARD_CONTAINER =0;    
	public static final int OFFSHORE =  0;                
	public static final int ON_CALL_PICKUP = 0;           
	public static final int OTHER =  20;                   
	public static final int OUT_OF_DELIVERY_AREA = 0;     
	public static final int OUT_OF_PICKUP_AREA = 0;       
	public static final int OVERSIZE = 0;                 
	public static final int PRIORITY_ALERT =0;            
	public static final int RESIDENTIAL_DELIVERY =0;      
	public static final int RESIDENTIAL_PICKUP =0;        
	public static final int RETURN_LABEL =0;              
	public static final int SATURDAY_DELIVERY = 7;        
	public static final int SATURDAY_PICKUP =0;           
	public static final int SIGNATURE_OPTION = 40;         
	public static final int THIRD_PARTY_CONSIGNEE =0;     
	public static final int TRANSMART_SERVICE_FEE =0;     
	public static final int DRY_ICE =  0;                 
	public static final int EXHIBITION = 0;               
	public static final int EXTREME_LENGTH =  0;          
	public static final int FLATBED =  0;                 
	public static final int FREIGHT_GUARANTEE =0;         
	public static final int ISLAND_DELIVERY = 0;          
	public static final int ISLAND_PICKUP = 0;            
	public static final int LIFTGATE_DELIVERY = 0;        
	public static final int LIFTGATE_PICKUP = 0;          
	public static final int LIMITED_ACCESS_DELIVERY = 0;  
	public static final int LIMITED_ACCESS_PICKUP = 0;    
	public static final int METRO_DELIVERY =0;            
	public static final int METRO_PICKUP =0;              
	public static final int OVER_DIMENSION =  22;          
	public static final int PRE_DELIVERY_NOTIFICATION = 0;
	public static final int PROTECTION_FROM_FREEZING =0;  
	public static final int REGIONAL_MALL_DELIVERY = 0;   
	public static final int REGIONAL_MALL_PICKUP = 0;    */ 

               
	
		/*public static final String ADDITIONAL_HANDLING = ""	;	
		public static final String APPOINTMENT_DELIVERY = "";	    
		public static final String BROKER_SELECT_OPTION = "";	     
		public static final String CANADIAN_DESTINATION = "";	      
		public static final String CLEARANCE_ENTRY_FEE = ""	;	       
		public static final String COD = "";                      
		public static final String DANGEROUS_GOODS = "Dangerous Goods";	         
		public static final String DELIVERY_AREA = "";	             
		public static final String DELIVERY_SIGNATURE_OPTIONS = "";	 
		public static final String EMAIL_LABEL = "";	               
		public static final String EUROPE_FIRST = "";	              
		public static final String EXPORT = ""	;	                    
		public static final String FEDEX_TAG = ""	;	                 
		public static final String FUEL = "Fuel";	                     
		public static final String HOME_DELIVERY_APPOINTMENT = "";	 
		public static final String HOME_DELIVERY_DATE_CERTAIN = "";	
		public static final String HOME_DELIVERY_EVENING = "";	     
		public static final String INSIDE_DELIVERY = "";	          
		public static final String INSIDE_PICKUP = "";	             
		public static final String INSURED_VALUE = "";	             
		public static final String INTERHAWAII = ""	;	               
		public static final String NON_STANDARD_CONTAINER = "";    
		public static final String OFFSHORE = "Offshore";                  
		public static final String ON_CALL_PICKUP = "";            
		public static final String OTHER = "Other";                   
		public static final String OUT_OF_DELIVERY_AREA = "";      
		public static final String OUT_OF_PICKUP_AREA = "";        
		public static final String OVERSIZE = ""	;                 
		public static final String PRIORITY_ALERT = ""	;            
		public static final String RESIDENTIAL_DELIVERY = "Residential Delivery";      
		public static final String RESIDENTIAL_PICKUP = "";        
		public static final String RETURN_LABEL = "";              
		public static final String SATURDAY_DELIVERY = "Saturday Service";        
		public static final String SATURDAY_PICKUP = ""	;           
		public static final String SIGNATURE_OPTION = "Signature Required";         
		public static final String THIRD_PARTY_CONSIGNEE = "";     
		public static final String TRANSMART_SERVICE_FEE ="";     
		public static final String DRY_ICE = ""	;                   
		public static final String EXHIBITION = ""	;                
		public static final String EXTREME_LENGTH = ""	;            
		public static final String FLATBED = ""	;                   
		public static final String FREIGHT_GUARANTEE = "";        
		public static final String ISLAND_DELIVERY  = "";           
		public static final String ISLAND_PICKUP = "";             
		public static final String LIFTGATE_DELIVERY = "";         
		public static final String LIFTGATE_PICKUP = "";           
		public static final String LIMITED_ACCESS_DELIVERY = "";   
		public static final String LIMITED_ACCESS_PICKUP = "";     
		public static final String METRO_DELIVERY = "";            
		public static final String METRO_PICKUP = "";              
		public static final String OVER_DIMENSION = "Over Weight/Size Surcharge";          
		public static final String PRE_DELIVERY_NOTIFICATION = ""; 
		public static final String PROTECTION_FROM_FREEZING = "";  
		public static final String REGIONAL_MALL_DELIVERY = "";    
		public static final String REGIONAL_MALL_PICKUP = "";      

	*/
	
	
	
	
	
	/*private static String SURCHARGE_NON_PACKAGED_GOODS_STRING = "Non Packaged Goods";
	private static String SURCHARGE_SATURDAY_SERVICE_STRING = "Saturday Service";
	private static String SURCHARGE_DANGEROUS_GOODS_STRING = "Dangerous Goods";
	private static String SURCHARGE_INSURANCE_CHARGE_PERCENT_STRING = "Insurance";
	private static String SURCHARGE_INSURANCE_MINIMUM_STRING = "Insurance";
	private static String SURCHARGE_COLLECT_STRING = "Collect";
	private static String SURCHARGE_BEYOND_CHARGE_STRING = "Beyond";
	private static String SURCHARGE_RURAL_CHARGE_STRING = "Rural";
	private static String SURCHARGE_SURCHARGE_EXPRESS_CHEQUE_STRING = "Express Cheque";
	private static String SURCHARGE_RESIDENTIAL_DELIVERY_STRING = "Residential Delivery";
	private static String SURCHARGE_OUT_OF_DELIVERY_AREA_STRING = "Out of Delivery Area";
	private static String SURCHARGE_OUT_OF_PICKUP_AREA_STRING = "Out of Pickup Area";
	private static String SURCHARGE_SATURDAY_PICKUP_STRING = "Saturday Pickup";
	private static String SURCHARGE_OTHER_STRING = "Other";
	private static String SURCHARGE_COD_STRING = "COD Fee";
	private static String SURCHARGE_OVERWEIGHT_STRING = "Over Weight/Size Surcharge";
	private static String SURCHARGE_DELIVERY_TAILGATE_STRING = "Delivery Tailgate";
	private static String SURCHARGE_PICKUP_TAILGATE_STRING = "Pickup Tailgate";
	private static String SURCHARGE_INSIDE_DELIVERY_STRING = "Inside Delivery";
	private static String SURCHARGE_DELIVERY_APPT_STRING = "Delivery Appointment";
	private static String SURCHARGE_FREIGHT_STRING = "Freight or Base";
	private static String SURCHARGE_FUEL_STRING = "Fuel";	
	private static String SURCHARGE_OFFSHORE_STRING = "Offshore";
	private static String SURCHARGE_SIGNATURE_REQUIRED_STRING = "Signature Required";
	private static String SURCHARGE_MISCELLANEOUS_STRING = "Miscellaneous Charge";
	private static String SURCHARGE_SCHEDULE_PICKUP_STRING = "Pickup Charge";*/


}
