
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T21:31:27.872-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "PickupService",
                      portName = "PickupPort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Pickup/v1.1",
                      wsdlLocation = "Pickup.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPortType")
                      
public class PickupPortTypeImpl implements PickupPortType {

    private static final Logger LOG = Logger.getLogger(PickupPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPortType#processPickupCreation(com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupCreationRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupCreationResponse processPickupCreation(PickupCreationRequest body,UPSSecurity upsSecurity) throws PickupCreationErrorMessage    { 
        LOG.info("Executing operation processPickupCreation");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupCreationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PickupCreationErrorMessage("PickupCreationErrorMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPortType#processPickupPendingStatus(com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPendingStatusRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPendingStatusResponse processPickupPendingStatus(PickupPendingStatusRequest body,UPSSecurity upsSecurity) throws PickupPendingStatusErrorMessage    { 
        LOG.info("Executing operation processPickupPendingStatus");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPendingStatusResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PickupPendingStatusErrorMessage("PickupPendingStatusErrorMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPortType#processPickupCancel(com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupCancelRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupCancelResponse processPickupCancel(PickupCancelRequest body,UPSSecurity upsSecurity) throws PickupCancelErrorMessage    { 
        LOG.info("Executing operation processPickupCancel");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupCancelResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PickupCancelErrorMessage("PickupCancelErrorMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupPortType#processPickupRate(com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupRateRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupRateResponse processPickupRate(PickupRateRequest body,UPSSecurity upsSecurity) throws PickupRateErrorMessage    { 
        LOG.info("Executing operation processPickupRate");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy.PickupRateResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PickupRateErrorMessage("PickupRateErrorMessage...");
    }

}
