package com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T21:31:27.888-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Pickup/v1.1", name = "PickupPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PickupPortType {

    @WebResult(name = "PickupCreationResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1", partName = "Body")
    @WebMethod(operationName = "ProcessPickupCreation", action = "http://onlinetools.ups.com/webservices/PickupBinding/v1.1")
    public PickupCreationResponse processPickupCreation(
        @WebParam(partName = "Body", name = "PickupCreationRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")
        PickupCreationRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws PickupCreationErrorMessage;

    @WebResult(name = "PickupPendingStatusResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1", partName = "Body")
    @WebMethod(operationName = "ProcessPickupPendingStatus", action = "http://onlinetools.ups.com/webservices/PickupBinding/v1.1")
    public PickupPendingStatusResponse processPickupPendingStatus(
        @WebParam(partName = "Body", name = "PickupPendingStatusRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")
        PickupPendingStatusRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws PickupPendingStatusErrorMessage;

    @WebResult(name = "PickupCancelResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1", partName = "Body")
    @WebMethod(operationName = "ProcessPickupCancel", action = "http://onlinetools.ups.com/webservices/PickupBinding/v1.1")
    public PickupCancelResponse processPickupCancel(
        @WebParam(partName = "Body", name = "PickupCancelRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")
        PickupCancelRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws PickupCancelErrorMessage;

    @WebResult(name = "PickupRateResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1", partName = "Body")
    @WebMethod(operationName = "ProcessPickupRate", action = "http://onlinetools.ups.com/webservices/PickupBinding/v1.1")
    public PickupRateResponse processPickupRate(
        @WebParam(partName = "Body", name = "PickupRateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Pickup/v1.1")
        PickupRateRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws PickupRateErrorMessage;
}
