
package com.meritconinc.shiplinx.carrier.ups.ws.pickup.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T21:31:27.895-05:00
 * Generated source version: 2.5.0
 * 
 */
 
public class PickupPortType_PickupPort_Server{

    protected PickupPortType_PickupPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new PickupPortTypeImpl();
        String address = "https://wwwcie.ups.com/webservices/Pickup";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new PickupPortType_PickupPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
