package com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * Service Contract Class - TrackingServiceContract
 *
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:52:55.417-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://purolator.com/pws/service/v1", name = "TrackingServiceContract")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TrackingServiceContract {

    /**
     * TrackPackagesByReference
     * @param request TrackPackagesByReferenceRequest
     * @return TrackPackagesByReferenceResponse
     */
    @WebResult(name = "TrackPackagesByReferenceResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "TrackPackagesByReferenceResponse")
    @Action(input = "http://purolator.com/pws/service/v1/TrackPackagesByReference", output = "http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByReferenceResponse", fault = {@FaultAction(className = TrackingServiceContractTrackPackagesByReferenceValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByReferenceValidationFaultFault")})
    @WebMethod(operationName = "TrackPackagesByReference", action = "http://purolator.com/pws/service/v1/TrackPackagesByReference")
    public TrackPackagesByReferenceResponseContainer trackPackagesByReference(
        @WebParam(partName = "TrackPackagesByReferenceRequest", name = "TrackPackagesByReferenceRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        TrackPackagesByReferenceRequestContainer trackPackagesByReferenceRequest
    ) throws TrackingServiceContractTrackPackagesByReferenceValidationFaultFaultFaultMessage;

    /**
     * Track Packages By Pin
     * @param request TrackPackagesByPinRequest
     * @return TrackPackagesByPinResponse
     */
    @WebResult(name = "TrackPackagesByPinResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "TrackPackagesByPinResponse")
    @Action(input = "http://purolator.com/pws/service/v1/TrackPackagesByPin", output = "http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinResponse", fault = {@FaultAction(className = TrackingServiceContractTrackPackagesByPinValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/TrackingServiceContract/TrackPackagesByPinValidationFaultFault")})
    @WebMethod(operationName = "TrackPackagesByPin", action = "http://purolator.com/pws/service/v1/TrackPackagesByPin")
    public TrackPackagesByPinResponseContainer trackPackagesByPin(
        @WebParam(partName = "TrackPackagesByPinRequest", name = "TrackPackagesByPinRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        TrackPackagesByPinRequestContainer trackPackagesByPinRequest
    ) throws TrackingServiceContractTrackPackagesByPinValidationFaultFaultFaultMessage;

    /**
     * GetDeliveryDetails
     * @param request GetDeliveryDetailsRequest
     * @return GetDeliveryDetailsResponse
     */
    @WebResult(name = "GetDeliveryDetailsResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetDeliveryDetailsResponse")
    @Action(input = "http://purolator.com/pws/service/v1/GetDeliveryDetails", output = "http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsResponse", fault = {@FaultAction(className = TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/TrackingServiceContract/GetDeliveryDetailsValidationFaultFault")})
    @WebMethod(operationName = "GetDeliveryDetails", action = "http://purolator.com/pws/service/v1/GetDeliveryDetails")
    public GetDeliveryDetailsResponseContainer getDeliveryDetails(
        @WebParam(partName = "GetDeliveryDetailsRequest", name = "GetDeliveryDetailsRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        GetDeliveryDetailsRequestContainer getDeliveryDetailsRequest
    ) throws TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage;
}
