
package com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:52:55.400-04:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ValidationFault", targetNamespace = "http://www.microsoft.com/practices/EnterpriseLibrary/2007/01/wcf/validation")
public class TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage extends Exception {
    
    private com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.ValidationFault validationFault;

    public TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage() {
        super();
    }
    
    public TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage(String message) {
        super(message);
    }
    
    public TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage(String message, com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.ValidationFault validationFault) {
        super(message);
        this.validationFault = validationFault;
    }

    public TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage(String message, com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.ValidationFault validationFault, Throwable cause) {
        super(message, cause);
        this.validationFault = validationFault;
    }

    public com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.ValidationFault getFaultInfo() {
        return this.validationFault;
    }
}
