
package com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:52:55.424-04:00
 * Generated source version: 2.5.2
 * 
 */
 
public class TrackingServiceContract_TrackingServiceEndpoint_Server{

    protected TrackingServiceContract_TrackingServiceEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TrackingServiceContractImpl();
        String address = "https://webservices.purolator.com/EWS/V1/Tracking/TrackingService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new TrackingServiceContract_TrackingServiceEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
