
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:52:55.407-04:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "TrackingService",
                      portName = "TrackingServiceEndpoint",
                      targetNamespace = "http://purolator.com/pws/service/v1",
                      wsdlLocation = "TrackingService.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackingServiceContract")
                      
public class TrackingServiceContractImpl implements TrackingServiceContract {

    private static final Logger LOG = Logger.getLogger(TrackingServiceContractImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackingServiceContract#trackPackagesByReference(com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackPackagesByReferenceRequestContainer  trackPackagesByReferenceRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackPackagesByReferenceResponseContainer trackPackagesByReference(TrackPackagesByReferenceRequestContainer trackPackagesByReferenceRequest) throws TrackingServiceContractTrackPackagesByReferenceValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation trackPackagesByReference");
        System.out.println(trackPackagesByReferenceRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackPackagesByReferenceResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TrackingServiceContractTrackPackagesByReferenceValidationFaultFaultFaultMessage("TrackingServiceContract_TrackPackagesByReference_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackingServiceContract#trackPackagesByPin(com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackPackagesByPinRequestContainer  trackPackagesByPinRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackPackagesByPinResponseContainer trackPackagesByPin(TrackPackagesByPinRequestContainer trackPackagesByPinRequest) throws TrackingServiceContractTrackPackagesByPinValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation trackPackagesByPin");
        System.out.println(trackPackagesByPinRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackPackagesByPinResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TrackingServiceContractTrackPackagesByPinValidationFaultFaultFaultMessage("TrackingServiceContract_TrackPackagesByPin_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.TrackingServiceContract#getDeliveryDetails(com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.GetDeliveryDetailsRequestContainer  getDeliveryDetailsRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.GetDeliveryDetailsResponseContainer getDeliveryDetails(GetDeliveryDetailsRequestContainer getDeliveryDetailsRequest) throws TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation getDeliveryDetails");
        System.out.println(getDeliveryDetailsRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.tracking.proxy.GetDeliveryDetailsResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TrackingServiceContractGetDeliveryDetailsValidationFaultFaultFaultMessage("TrackingServiceContract_GetDeliveryDetails_ValidationFaultFault_FaultMessage...");
    }

}
