package com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.com.purolator.pws.service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.com.purolator.pws.datatypes.v1.GetPickUpRequestContainer;
import com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.com.purolator.pws.datatypes.v1.GetPickUpResponseContainer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 *
 */
@WebService(name = "FreightPickUpServiceContract", targetNamespace = "http://purolator.com/pws/service/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.org.datacontract.schemas._2004._07.microsoft_practices_enterpriselibrary_validation_integration.ObjectFactory.class,
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.com.purolator.pws.datatypes.v1.ObjectFactory.class,
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.com.microsoft.practices.enterpriselibrary._2007._01.wcf.validation.ObjectFactory.class,
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.pickup.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class
})
public interface FreightPickUpServiceContract {


 /**
 *
 * @param freightGetPickUpRequest
 * @return
 * returns com.purolator.pws.datatypes.v1.GetPickUpResponseContainer
 * @throws FreightPickUpServiceContractGetFreightPickupValidationFaultFaultFaultMessage
 */
 @WebMethod(operationName = "GetFreightPickup", action = "http://purolator.com/pws/service/v1/Freight/GetFreightPickup")
 @WebResult(name = "GetPickUpResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetPickUpResponse")
 public GetPickUpResponseContainer getFreightPickup(
 @WebParam(name = "FreightGetPickUpRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "FreightGetPickUpRequest")
 GetPickUpRequestContainer freightGetPickUpRequest)
 throws FreightPickUpServiceContractGetFreightPickupValidationFaultFaultFaultMessage
 ;

}