
package com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T08:17:40.061-05:00
 * Generated source version: 2.5.0
 * 
 */
 
public class FreightShipPortType_FreightShipPort_Server{

    protected FreightShipPortType_FreightShipPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new FreightShipPortTypeImpl();
        String address = "https://wwwcie.ups.com/webservices/FreightShip";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new FreightShipPortType_FreightShipPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
