
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T08:17:40.037-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "FreightShipService",
                      portName = "FreightShipPort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0",
                      wsdlLocation = "FreightShip.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy.FreightShipPortType")
                      
public class FreightShipPortTypeImpl implements FreightShipPortType {

    private static final Logger LOG = Logger.getLogger(FreightShipPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy.FreightShipPortType#processShipment(com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy.FreightShipRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy.FreightShipResponse processShipment(FreightShipRequest body,UPSSecurity upsSecurity) throws ShipErrorMessage    { 
        LOG.info("Executing operation processShipment");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy.FreightShipResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShipErrorMessage("ShipErrorMessage...");
    }

}
