package com.meritconinc.shiplinx.carrier.ups.ws.freightship.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T08:17:40.054-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightShip/v1.0", name = "FreightShipPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FreightShipPortType {

    @WebResult(name = "FreightShipResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightShip/v1.0", partName = "Body")
    @WebMethod(operationName = "ProcessShipment", action = "http://onlinetools.ups.com/webservices/FreightShipBinding/v1.0")
    public FreightShipResponse processShipment(
        @WebParam(partName = "Body", name = "FreightShipRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/FreightShip/v1.0")
        FreightShipRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws ShipErrorMessage;
}
