
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-16T20:28:49.602-04:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ShippingDocumentsService",
                      portName = "ShippingDocumentsServiceEndpoint",
                      targetNamespace = "http://purolator.com/pws/service/v1",
                      wsdlLocation = "ShippingDocumentsService.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.ShippingDocumentsServiceContract")
                      
public class ShippingDocumentsServiceContractImpl implements ShippingDocumentsServiceContract {

    private static final Logger LOG = Logger.getLogger(ShippingDocumentsServiceContractImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.ShippingDocumentsServiceContract#getShipmentManifestDocument(com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.GetShipmentManifestDocumentRequestContainer  getShipmentManifestDocumentRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.GetShipmentManifestDocumentResponseContainer getShipmentManifestDocument(GetShipmentManifestDocumentRequestContainer getShipmentManifestDocumentRequest) throws ShippingDocumentsServiceContractGetShipmentManifestDocumentValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation getShipmentManifestDocument");
        System.out.println(getShipmentManifestDocumentRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.GetShipmentManifestDocumentResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShippingDocumentsServiceContractGetShipmentManifestDocumentValidationFaultFaultFaultMessage("ShippingDocumentsServiceContract_GetShipmentManifestDocument_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.ShippingDocumentsServiceContract#getDocuments(com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.GetDocumentsRequestContainer  getDocumentsRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.GetDocumentsResponseContainer getDocuments(GetDocumentsRequestContainer getDocumentsRequest) throws ShippingDocumentsServiceContractGetDocumentsValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation getDocuments");
        System.out.println(getDocumentsRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy.GetDocumentsResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShippingDocumentsServiceContractGetDocumentsValidationFaultFaultFaultMessage("ShippingDocumentsServiceContract_GetDocuments_ValidationFaultFault_FaultMessage...");
    }

}
