package com.meritconinc.shiplinx.carrier.purolator.ws.shippingdocuments.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * Service Contract Class - ShippingDocumentsServiceContract
 *
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-16T20:28:49.613-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://purolator.com/pws/service/v1", name = "ShippingDocumentsServiceContract")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ShippingDocumentsServiceContract {

    /**
     * GetShipemntManifestDocument
     * @param request GetShipmentManifestDocumentRequest
     * @return GetShipmentManifestDocumentResponse
     *       
     */
    @WebResult(name = "GetShipmentManifestDocumentResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetShipmentManifestDocumentResponse")
    @Action(input = "http://purolator.com/pws/service/v1/GetShipmentManifestDocument", output = "http://purolator.com/pws/service/v1/ShippingDocumentsServiceContract/GetShipmentManifestDocumentResponse", fault = {@FaultAction(className = ShippingDocumentsServiceContractGetShipmentManifestDocumentValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ShippingDocumentsServiceContract/GetShipmentManifestDocumentValidationFaultFault")})
    @WebMethod(operationName = "GetShipmentManifestDocument", action = "http://purolator.com/pws/service/v1/GetShipmentManifestDocument")
    public GetShipmentManifestDocumentResponseContainer getShipmentManifestDocument(
        @WebParam(partName = "GetShipmentManifestDocumentRequest", name = "GetShipmentManifestDocumentRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        GetShipmentManifestDocumentRequestContainer getShipmentManifestDocumentRequest
    ) throws ShippingDocumentsServiceContractGetShipmentManifestDocumentValidationFaultFaultFaultMessage;

    /**
     * GetDocuments
     * @param request GetDocumentsRequest
     * @return GetDocumentsResponse
     */
    @WebResult(name = "GetDocumentsResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetDocumentsResponse")
    @Action(input = "http://purolator.com/pws/service/v1/GetDocuments", output = "http://purolator.com/pws/service/v1/ShippingDocumentsServiceContract/GetDocumentsResponse", fault = {@FaultAction(className = ShippingDocumentsServiceContractGetDocumentsValidationFaultFaultFaultMessage.class, value = "http://purolator.com/pws/service/v1/ShippingDocumentsServiceContract/GetDocumentsValidationFaultFault")})
    @WebMethod(operationName = "GetDocuments", action = "http://purolator.com/pws/service/v1/GetDocuments")
    public GetDocumentsResponseContainer getDocuments(
        @WebParam(partName = "GetDocumentsRequest", name = "GetDocumentsRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1")
        GetDocumentsRequestContainer getDocumentsRequest
    ) throws ShippingDocumentsServiceContractGetDocumentsValidationFaultFaultFaultMessage;
}
