
package com.meritconinc.shiplinx.carrier.eshipplus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "eShipPlusWSv4Soap", targetNamespace = "http://www.eshipplus.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EShipPlusWSv4Soap {


    /**
     * Returns List of Accessorial Services available.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSAccessorialService
     */
    @WebMethod(operationName = "GetAccessorialServices", action = "http://www.eshipplus.com/GetAccessorialServices")
    @WebResult(name = "GetAccessorialServicesResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetAccessorialServices", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetAccessorialServices")
    @ResponseWrapper(localName = "GetAccessorialServicesResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetAccessorialServicesResponse")
    public ArrayOfWSAccessorialService getAccessorialServices(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns list of LTL freight classes supported by service.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSFreightClass
     */
    @WebMethod(operationName = "GetLTLFreightClasses", action = "http://www.eshipplus.com/GetLTLFreightClasses")
    @WebResult(name = "GetLTLFreightClassesResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetLTLFreightClasses", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetLTLFreightClasses")
    @ResponseWrapper(localName = "GetLTLFreightClassesResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetLTLFreightClassesResponse")
    public ArrayOfWSFreightClass getLTLFreightClasses(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns list of item package types available.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSItemPackage
     */
    @WebMethod(operationName = "GetItemPackaging", action = "http://www.eshipplus.com/GetItemPackaging")
    @WebResult(name = "GetItemPackagingResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetItemPackaging", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetItemPackaging")
    @ResponseWrapper(localName = "GetItemPackagingResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetItemPackagingResponse")
    public ArrayOfWSItemPackage getItemPackaging(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns list of serviced countries.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSCountry
     */
    @WebMethod(operationName = "GetCountries", action = "http://www.eshipplus.com/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetCountriesResponse")
    public ArrayOfWSCountry getCountries(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns list of time string objects acceptable by service.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSTime2
     */
    @WebMethod(operationName = "GetTimes", action = "http://www.eshipplus.com/GetTimes")
    @WebResult(name = "GetTimesResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetTimes", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetTimes")
    @ResponseWrapper(localName = "GetTimesResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetTimesResponse")
    public ArrayOfWSTime2 getTimes(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns single object containing Accessorial Services, LTL Freight Classes, item package types, countries and times.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSOptions
     */
    @WebMethod(operationName = "GetInputOptions", action = "http://www.eshipplus.com/GetInputOptions")
    @WebResult(name = "GetInputOptionsResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetInputOptions", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInputOptions")
    @ResponseWrapper(localName = "GetInputOptionsResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInputOptionsResponse")
    public WSOptions getInputOptions(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns list of custom reference fields specific to account.
     * 
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSReference
     */
    @WebMethod(operationName = "GetCustomerCustomReferences", action = "http://www.eshipplus.com/GetCustomerCustomReferences")
    @WebResult(name = "GetCustomerCustomReferencesResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetCustomerCustomReferences", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetCustomerCustomReferences")
    @ResponseWrapper(localName = "GetCustomerCustomReferencesResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetCustomerCustomReferencesResponse")
    public ArrayOfWSReference getCustomerCustomReferences(
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns customer purchase order.
     * 
     * @param authenticationToken
     * @param poNumber
     * @return
     *     returns com.eshipplus.WSCustomerPONumber
     */
    @WebMethod(operationName = "RetrievePONumber", action = "http://www.eshipplus.com/RetrievePONumber")
    @WebResult(name = "RetrievePONumberResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "RetrievePONumber", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RetrievePONumber")
    @ResponseWrapper(localName = "RetrievePONumberResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RetrievePONumberResponse")
    public WSCustomerPONumber retrievePONumber(
        @WebParam(name = "poNumber", targetNamespace = "http://www.eshipplus.com/")
        String poNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Deletes a PO Number entry.
     * 
     * @param authenticationToken
     * @param poNumber
     * @return
     *     returns com.eshipplus.WSReturn
     */
    @WebMethod(operationName = "DeletePONumber", action = "http://www.eshipplus.com/DeletePONumber")
    @WebResult(name = "DeletePONumberResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "DeletePONumber", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.DeletePONumber")
    @ResponseWrapper(localName = "DeletePONumberResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.DeletePONumberResponse")
    public WSReturn deletePONumber(
        @WebParam(name = "poNumber", targetNamespace = "http://www.eshipplus.com/")
        String poNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Updates a PO Number entry.
     * 
     * @param customerPONumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSReturn
     */
    @WebMethod(operationName = "UpdatePONumber", action = "http://www.eshipplus.com/UpdatePONumber")
    @WebResult(name = "UpdatePONumberResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "UpdatePONumber", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.UpdatePONumber")
    @ResponseWrapper(localName = "UpdatePONumberResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.UpdatePONumberResponse")
    public WSReturn updatePONumber(
        @WebParam(name = "customerPONumber", targetNamespace = "http://www.eshipplus.com/")
        WSCustomerPONumber customerPONumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Adds a PO Number entry.
     * 
     * @param customerPONumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSReturn
     */
    @WebMethod(operationName = "AddPONumber", action = "http://www.eshipplus.com/AddPONumber")
    @WebResult(name = "AddPONumberResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "AddPONumber", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.AddPONumber")
    @ResponseWrapper(localName = "AddPONumberResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.AddPONumberResponse")
    public WSReturn addPONumber(
        @WebParam(name = "customerPONumber", targetNamespace = "http://www.eshipplus.com/")
        WSCustomerPONumber customerPONumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Adds a PO Number entry.
     * 
     * @param authenticationToken
     * @param customerPONumbers
     * @return
     *     returns com.eshipplus.WSReturn
     */
    @WebMethod(operationName = "AddPONumbers", action = "http://www.eshipplus.com/AddPONumbers")
    @WebResult(name = "AddPONumbersResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "AddPONumbers", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.AddPONumbers")
    @ResponseWrapper(localName = "AddPONumbersResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.AddPONumbersResponse")
    public WSReturn addPONumbers(
        @WebParam(name = "customerPONumbers", targetNamespace = "http://www.eshipplus.com/")
        ArrayOfWSCustomerPONumber customerPONumbers,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns status of a booking request.
     * 
     * @param bookingNumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSBookingRequestStatus
     */
    @WebMethod(operationName = "GetBookingRequestStatus", action = "http://www.eshipplus.com/GetBookingRequestStatus")
    @WebResult(name = "GetBookingRequestStatusResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetBookingRequestStatus", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetBookingRequestStatus")
    @ResponseWrapper(localName = "GetBookingRequestStatusResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetBookingRequestStatusResponse")
    public WSBookingRequestStatus getBookingRequestStatus(
        @WebParam(name = "bookingNumber", targetNamespace = "http://www.eshipplus.com/")
        String bookingNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns status of a shipment.
     * 
     * @param shipmentNumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSShipmentStatus
     */
    @WebMethod(operationName = "GetShipmentStatus", action = "http://www.eshipplus.com/GetShipRequestBookingRequestCancellationResponsementStatus")
    @WebResult(name = "GetShipmentStatusResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetShipmentStatus", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetShipmentStatus")
    @ResponseWrapper(localName = "GetShipmentStatusResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetShipmentStatusResponse")
    public WSShipmentStatus getShipmentStatus(
        @WebParam(name = "shipmentNumber", targetNamespace = "http://www.eshipplus.com/")
        String shipmentNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Processes a shipment cancellation.
     * 
     * @param shipmentNumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSReturn
     */
    @WebMethod(operationName = "RequestShipmentCancellation", action = "http://www.eshipplus.com/RequestShipmentCancellation")
    @WebResult(name = "RequestShipmentCancellationResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "RequestShipmentCancellation", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RequestShipmentCancellation")
    @ResponseWrapper(localName = "RequestShipmentCancellationResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RequestShipmentCancellationResponse")
    public WSReturn requestShipmentCancellation(
        @WebParam(name = "shipmentNumber", targetNamespace = "http://www.eshipplus.com/")
        String shipmentNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Processes a booking reqeust cancellation.
     * 
     * @param bookingNumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSReturn
     */
    @WebMethod(operationName = "RequestBookingRequestCancellation", action = "http://www.eshipplus.com/RequestBookingRequestCancellation")
    @WebResult(name = "RequestBookingRequestCancellationResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "RequestBookingRequestCancellation", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RequestBookingRequestCancellation")
    @ResponseWrapper(localName = "RequestBookingRequestCancellationResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RequestBookingRequestCancellationResponse")
    public WSReturn requestBookingRequestCancellation(
        @WebParam(name = "bookingNumber", targetNamespace = "http://www.eshipplus.com/")
        String bookingNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns invoice record detail.
     * 
     * @param authenticationToken
     * @param invoiceNumber
     * @return
     *     returns com.eshipplus.WSInvoice
     */
    @WebMethod(operationName = "GetInvoice", action = "http://www.eshipplus.com/GetInvoice")
    @WebResult(name = "GetInvoiceResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetInvoice", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoice")
    @ResponseWrapper(localName = "GetInvoiceResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoiceResponse")
    public WSInvoice getInvoice(
        @WebParam(name = "invoiceNumber", targetNamespace = "http://www.eshipplus.com/")
        String invoiceNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns invoice record details.
     * 
     * @param startdate
     * @param authenticationToken
     * @param endDate
     * @return
     *     returns com.eshipplus.ArrayOfWSInvoiceSummary
     */
    @WebMethod(operationName = "GetInvoicesByDueDate", action = "http://www.eshipplus.com/GetInvoicesByDueDate")
    @WebResult(name = "GetInvoicesByDueDateResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetInvoicesByDueDate", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoicesByDueDate")
    @ResponseWrapper(localName = "GetInvoicesByDueDateResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoicesByDueDateResponse")
    public ArrayOfWSInvoiceSummary getInvoicesByDueDate(
        @WebParam(name = "startdate", targetNamespace = "http://www.eshipplus.com/")
        XMLGregorianCalendar startdate,
        @WebParam(name = "endDate", targetNamespace = "http://www.eshipplus.com/")
        XMLGregorianCalendar endDate,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns invoice record details.
     * 
     * @param startdate
     * @param authenticationToken
     * @param endDate
     * @return
     *     returns com.eshipplus.ArrayOfWSInvoiceSummary
     */
    @WebMethod(operationName = "GetInvoicesByDate", action = "http://www.eshipplus.com/GetInvoicesByDate")
    @WebResult(name = "GetInvoicesByDateResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetInvoicesByDate", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoicesByDate")
    @ResponseWrapper(localName = "GetInvoicesByDateResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoicesByDateResponse")
    public ArrayOfWSInvoiceSummary getInvoicesByDate(
        @WebParam(name = "startdate", targetNamespace = "http://www.eshipplus.com/")
        XMLGregorianCalendar startdate,
        @WebParam(name = "endDate", targetNamespace = "http://www.eshipplus.com/")
        XMLGregorianCalendar endDate,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Returns invoice record details for a particular shipment.
     * 
     * @param shipmentNumber
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.ArrayOfWSInvoiceSummary
     */
    @WebMethod(operationName = "GetInvoicesForShipment", action = "http://www.eshipplus.com/GetInvoicesForShipment")
    @WebResult(name = "GetInvoicesForShipmentResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "GetInvoicesForShipment", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoicesForShipment")
    @ResponseWrapper(localName = "GetInvoicesForShipmentResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.GetInvoicesForShipmentResponse")
    public ArrayOfWSInvoiceSummary getInvoicesForShipment(
        @WebParam(name = "shipmentNumber", targetNamespace = "http://www.eshipplus.com/")
        String shipmentNumber,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Submits a loading booking request to operations department be covered.
     * 
     * @param request
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSBookingRequest
     */
    @WebMethod(operationName = "SubmitBookingRequest", action = "http://www.eshipplus.com/SubmitBookingRequest")
    @WebResult(name = "SubmitBookingRequestResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "SubmitBookingRequest", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.SubmitBookingRequest")
    @ResponseWrapper(localName = "SubmitBookingRequestResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.SubmitBookingRequestResponse")
    public WSBookingRequest submitBookingRequest(
        @WebParam(name = "request", targetNamespace = "http://www.eshipplus.com/")
        WSBookingRequest request,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Get shipping rates for submitted shipment.
     * 
     * @param shipment
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSShipment2
     */
    @WebMethod(operationName = "Rate", action = "http://www.eshipplus.com/Rate")
    @WebResult(name = "RateResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "Rate", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.Rate")
    @ResponseWrapper(localName = "RateResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.RateResponse")
    public WSShipment2 rate(
        @WebParam(name = "shipment", targetNamespace = "http://www.eshipplus.com/")
        WSShipment2 shipment,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

    /**
     * Book submitted shipment.
     * 
     * @param shipment
     * @param authenticationToken
     * @return
     *     returns com.eshipplus.WSShipment2
     */
    @WebMethod(operationName = "Book", action = "http://www.eshipplus.com/Book")
    @WebResult(name = "BookResult", targetNamespace = "http://www.eshipplus.com/")
    @RequestWrapper(localName = "Book", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.Book")
    @ResponseWrapper(localName = "BookResponse", targetNamespace = "http://www.eshipplus.com/", className = "com.eshipplus.BookResponse")
    public WSShipment2 book(
        @WebParam(name = "shipment", targetNamespace = "http://www.eshipplus.com/")
        WSShipment2 shipment,
        @WebParam(name = "AuthenticationToken", targetNamespace = "http://www.eshipplus.com/", header = true, partName = "AuthenticationToken")
        AuthenticationToken authenticationToken);

}
