package com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T22:11:53.382-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Ship/v1.0", name = "ShipPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ShipPortType {

    @WebResult(name = "ShipmentResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Ship/v1.0", partName = "Body")
    @WebMethod(operationName = "ProcessShipment", action = "http://onlinetools.ups.com/webservices/ShipBinding/v1.0")
    public ShipmentResponse processShipment(
        @WebParam(partName = "Body", name = "ShipmentRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Ship/v1.0")
        ShipmentRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws ShipmentErrorMessage;

    @WebResult(name = "ShipAcceptResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Ship/v1.0", partName = "Body")
    @WebMethod(operationName = "ProcessShipAccept", action = "http://onlinetools.ups.com/webservices/ShipBinding/v1.0")
    public ShipAcceptResponse processShipAccept(
        @WebParam(partName = "Body", name = "ShipAcceptRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Ship/v1.0")
        ShipAcceptRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws ShipAcceptErrorMessage;

    @WebResult(name = "ShipConfirmResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Ship/v1.0", partName = "Body")
    @WebMethod(operationName = "ProcessShipConfirm", action = "http://onlinetools.ups.com/webservices/ShipBinding/v1.0")
    public ShipConfirmResponse processShipConfirm(
        @WebParam(partName = "Body", name = "ShipConfirmRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Ship/v1.0")
        ShipConfirmRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws ShipConfirmErrorMessage;
}
