
package com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T22:11:53.311-05:00
 * Generated source version: 2.5.0
 * 
 */
public final class ShipPortType_ShipPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ups.com/WSDL/XOLTWS/Ship/v1.0", "ShipService");

    private ShipPortType_ShipPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ShipService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ShipService ss = new ShipService(wsdlURL, SERVICE_NAME);
        ShipPortType port = ss.getShipPort();  
        
        {
        System.out.println("Invoking processShipment...");
        com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.ShipmentRequest _processShipment_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.UPSSecurity _processShipment_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.ShipmentResponse _processShipment__return = port.processShipment(_processShipment_body, _processShipment_upsSecurity);
            System.out.println("processShipment.result=" + _processShipment__return);

        } catch (ShipmentErrorMessage e) { 
            System.out.println("Expected exception: ShipmentErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking processShipAccept...");
        com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.ShipAcceptRequest _processShipAccept_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.UPSSecurity _processShipAccept_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.ShipAcceptResponse _processShipAccept__return = port.processShipAccept(_processShipAccept_body, _processShipAccept_upsSecurity);
            System.out.println("processShipAccept.result=" + _processShipAccept__return);

        } catch (ShipAcceptErrorMessage e) { 
            System.out.println("Expected exception: ShipAcceptErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking processShipConfirm...");
        com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.ShipConfirmRequest _processShipConfirm_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.UPSSecurity _processShipConfirm_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.ship.proxy.ShipConfirmResponse _processShipConfirm__return = port.processShipConfirm(_processShipConfirm_body, _processShipConfirm_upsSecurity);
            System.out.println("processShipConfirm.result=" + _processShipConfirm__return);

        } catch (ShipConfirmErrorMessage e) { 
            System.out.println("Expected exception: ShipConfirmErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
