
package com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-12T21:59:51.050-04:00
 * Generated source version: 2.5.2
 * 
 */
public final class EstimatingServiceContract_EstimatingServiceEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://purolator.com/pws/service/v1", "EstimatingService");

    private EstimatingServiceContract_EstimatingServiceEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EstimatingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EstimatingService ss = new EstimatingService(wsdlURL, SERVICE_NAME);
        EstimatingServiceContract port = ss.getEstimatingServiceEndpoint();  
        
        {
        System.out.println("Invoking getQuickEstimate...");
        com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetQuickEstimateRequestContainer _getQuickEstimate_getQuickEstimateRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetQuickEstimateResponseContainer _getQuickEstimate__return = port.getQuickEstimate(_getQuickEstimate_getQuickEstimateRequest);
            System.out.println("getQuickEstimate.result=" + _getQuickEstimate__return);

        } catch (EstimatingServiceContractGetQuickEstimateValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: EstimatingServiceContract_GetQuickEstimate_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getFullEstimate...");
        com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetFullEstimateRequestContainer _getFullEstimate_getFullEstimateRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetFullEstimateResponseContainer _getFullEstimate__return = port.getFullEstimate(_getFullEstimate_getFullEstimateRequest);
            System.out.println("getFullEstimate.result=" + _getFullEstimate__return);

        } catch (EstimatingServiceContractGetFullEstimateValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: EstimatingServiceContract_GetFullEstimate_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
