package com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-12T21:59:51.175-04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "EstimatingService", 
                  wsdlLocation = "EstimatingService.wsdl",
                  targetNamespace = "http://purolator.com/pws/service/v1") 
public class EstimatingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://purolator.com/pws/service/v1", "EstimatingService");
    public final static QName EstimatingServiceEndpoint = new QName("http://purolator.com/pws/service/v1", "EstimatingServiceEndpoint");
    static {
        URL url = EstimatingService.class.getResource("EstimatingService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EstimatingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "EstimatingService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public EstimatingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EstimatingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstimatingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns EstimatingServiceContract
     */
    @WebEndpoint(name = "EstimatingServiceEndpoint")
    public EstimatingServiceContract getEstimatingServiceEndpoint() {
        return super.getPort(EstimatingServiceEndpoint, EstimatingServiceContract.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstimatingServiceContract
     */
    @WebEndpoint(name = "EstimatingServiceEndpoint")
    public EstimatingServiceContract getEstimatingServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(EstimatingServiceEndpoint, EstimatingServiceContract.class, features);
    }

}
