
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-12T21:59:51.144-04:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "EstimatingService",
                      portName = "EstimatingServiceEndpoint",
                      targetNamespace = "http://purolator.com/pws/service/v1",
                      wsdlLocation = "EstimatingService.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.EstimatingServiceContract")
                      
public class EstimatingServiceContractImpl implements EstimatingServiceContract {

    private static final Logger LOG = Logger.getLogger(EstimatingServiceContractImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.EstimatingServiceContract#getQuickEstimate(com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetQuickEstimateRequestContainer  getQuickEstimateRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetQuickEstimateResponseContainer getQuickEstimate(GetQuickEstimateRequestContainer getQuickEstimateRequest) throws EstimatingServiceContractGetQuickEstimateValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation getQuickEstimate");
        System.out.println(getQuickEstimateRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetQuickEstimateResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EstimatingServiceContractGetQuickEstimateValidationFaultFaultFaultMessage("EstimatingServiceContract_GetQuickEstimate_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.EstimatingServiceContract#getFullEstimate(com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetFullEstimateRequestContainer  getFullEstimateRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetFullEstimateResponseContainer getFullEstimate(GetFullEstimateRequestContainer getFullEstimateRequest) throws EstimatingServiceContractGetFullEstimateValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation getFullEstimate");
        System.out.println(getFullEstimateRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.estimating.proxy.GetFullEstimateResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EstimatingServiceContractGetFullEstimateValidationFaultFaultFaultMessage("EstimatingServiceContract_GetFullEstimate_ValidationFaultFault_FaultMessage...");
    }

}
