
package com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:43:59.767-04:00
 * Generated source version: 2.5.2
 * 
 */
public final class PickUpServiceContract_PickUpServiceEndpoint_Client {

    private static final QName SERVICE_NAME = new QName("http://purolator.com/pws/service/v1", "PickUpService");

    private PickUpServiceContract_PickUpServiceEndpoint_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PickUpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PickUpService ss = new PickUpService(wsdlURL, SERVICE_NAME);
        PickUpServiceContract port = ss.getPickUpServiceEndpoint();  
        
        {
        System.out.println("Invoking getPickUpHistory...");
        com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.GetPickUpHistoryRequestContainer _getPickUpHistory_getPickUpHistoryRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.GetPickUpHistoryResponseContainer _getPickUpHistory__return = port.getPickUpHistory(_getPickUpHistory_getPickUpHistoryRequest);
            System.out.println("getPickUpHistory.result=" + _getPickUpHistory__return);

        } catch (PickUpServiceContractGetPickUpHistoryValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: PickUpServiceContract_GetPickUpHistory_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking modifyPickUp...");
        com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.ModifyPickUpRequestContainer _modifyPickUp_modifyPickUpRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.ModifyPickUpResponseContainer _modifyPickUp__return = port.modifyPickUp(_modifyPickUp_modifyPickUpRequest);
            System.out.println("modifyPickUp.result=" + _modifyPickUp__return);

        } catch (PickUpServiceContractModifyPickUpValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: PickUpServiceContract_ModifyPickUp_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking voidPickUp...");
        com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.VoidPickUpRequestContainer _voidPickUp_voidPickUpRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.VoidPickUpResponseContainer _voidPickUp__return = port.voidPickUp(_voidPickUp_voidPickUpRequest);
            System.out.println("voidPickUp.result=" + _voidPickUp__return);

        } catch (PickUpServiceContractVoidPickUpValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: PickUpServiceContract_VoidPickUp_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking validatePickUp...");
        com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.ValidatePickUpRequestContainer _validatePickUp_validatePickUpRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.ValidatePickUpResponseContainer _validatePickUp__return = port.validatePickUp(_validatePickUp_validatePickUpRequest);
            System.out.println("validatePickUp.result=" + _validatePickUp__return);

        } catch (PickUpServiceContractValidatePickUpValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: PickUpServiceContract_ValidatePickUp_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking schedulePickUp...");
        com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.SchedulePickUpRequestContainer _schedulePickUp_schedulePickUpRequest = null;
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.pickup.proxy.SchedulePickUpResponseContainer _schedulePickUp__return = port.schedulePickUp(_schedulePickUp_schedulePickUpRequest);
            System.out.println("schedulePickUp.result=" + _schedulePickUp__return);

        } catch (PickUpServiceContractSchedulePickUpValidationFaultFaultFaultMessage e) { 
            System.out.println("Expected exception: PickUpServiceContract_SchedulePickUp_ValidationFaultFault_FaultMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
