/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meritconinc.shiplinx.api.model;

public class ImageElement {
	private java.lang.String created_at;

 	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getCreated_at() {
		return created_at;
	}

	private java.lang.String src;

 	public void setSrc(java.lang.String src) {
		this.src = src;
	}

	public java.lang.String getSrc() {
		return src;
	}

	private java.lang.Long id;

 	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getId() {
		return id;
	}

	private java.lang.Integer position;

 	public void setPosition(java.lang.Integer position) {
		this.position = position;
	}

	public java.lang.Integer getPosition() {
		return position;
	}

	private java.lang.String updated_at;

 	public void setUpdated_at(java.lang.String updated_at) {
		this.updated_at = updated_at;
	}

	public java.lang.String getUpdated_at() {
		return updated_at;
	}

	private java.lang.Integer product_id;

 	public void setProduct_id(java.lang.Integer product_id) {
		this.product_id = product_id;
	}

	public java.lang.Integer getProduct_id() {
		return product_id;
	}

	private java.lang.Object[] variant_ids;

 	public void setVariant_ids(java.lang.Object[] variant_ids) {
		this.variant_ids = variant_ids;
	}

	public java.lang.Object[] getVariant_ids() {
		return variant_ids;
	}

}