/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meritconinc.shiplinx.api.model;

public class ShopifyShop {
	private Shop shop;
	private Long customerId;

 	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Shop getShop() {
		return shop;
	}

	public Long getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}
	

}