/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.meritconinc.shiplinx.api.model;

import java.util.List;

public class ShopifyProduct {
	private List<ProductElement> products;

	public List<ProductElement> getProducts() {
		return products;
	}

	public void setProducts(List<ProductElement> products) {
		this.products = products;
	}
	public Long getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}
	private Long customerId;

  
}