
package com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-09T23:07:23.552-05:00
 * Generated source version: 2.5.0
 * 
 */
public final class FreightPickupPortType_FreightPickupPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ups.com/WSDL/XOLTWS/FreightPickup/v1.0", "FreightPickupService");

    private FreightPickupPortType_FreightPickupPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FreightPickupService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FreightPickupService ss = new FreightPickupService(wsdlURL, SERVICE_NAME);
        FreightPickupPortType port = ss.getFreightPickupPort();  
        
        {
        System.out.println("Invoking processFreightPickup...");
        com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupRequest _processFreightPickup_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.UPSSecurity _processFreightPickup_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupResponse _processFreightPickup__return = port.processFreightPickup(_processFreightPickup_body, _processFreightPickup_upsSecurity);
            System.out.println("processFreightPickup.result=" + _processFreightPickup__return);

        } catch (PickupErrorMessage e) { 
            System.out.println("Expected exception: PickupErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking processFreightCancelPickup...");
        com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightCancelPickupRequest _processFreightCancelPickup_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.UPSSecurity _processFreightCancelPickup_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightCancelPickupResponse _processFreightCancelPickup__return = port.processFreightCancelPickup(_processFreightCancelPickup_body, _processFreightCancelPickup_upsSecurity);
            System.out.println("processFreightCancelPickup.result=" + _processFreightCancelPickup__return);

        } catch (FreightCancelPickupErrorMessage e) { 
            System.out.println("Expected exception: FreightCancelPickupErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
