
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-09T23:07:23.606-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "FreightPickupService",
                      portName = "FreightPickupPort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/FreightPickup/v1.0",
                      wsdlLocation = "FreightPickup.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupPortType")
                      
public class FreightPickupPortTypeImpl implements FreightPickupPortType {

    private static final Logger LOG = Logger.getLogger(FreightPickupPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupPortType#processFreightPickup(com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupResponse processFreightPickup(FreightPickupRequest body,UPSSecurity upsSecurity) throws PickupErrorMessage    { 
        LOG.info("Executing operation processFreightPickup");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PickupErrorMessage("PickupErrorMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightPickupPortType#processFreightCancelPickup(com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightCancelPickupRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightCancelPickupResponse processFreightCancelPickup(FreightCancelPickupRequest body,UPSSecurity upsSecurity) throws FreightCancelPickupErrorMessage    { 
        LOG.info("Executing operation processFreightCancelPickup");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.freightpickup.proxy.FreightCancelPickupResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new FreightCancelPickupErrorMessage("FreightCancelPickupErrorMessage...");
    }

}
