//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.01 at 06:34:59 PM EST 
//


package com.meritconinc.shiplinx.carrier.dhl.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{http://www.dhl.com/datatypes}Request"/>
 *         &lt;element name="Requestor" type="{http://www.dhl.com/pickupdatatypes}Requestor"/>
 *         &lt;element name="Place" type="{http://www.dhl.com/pickupdatatypes}Place"/>
 *         &lt;element name="Pickup" type="{http://www.dhl.com/pickupdatatypes}Pickup"/>
 *         &lt;element name="PickupContact" type="{http://www.dhl.com/pickupdatatypes}contact"/>
 *         &lt;element name="ShipmentDetails" type="{http://www.dhl.com/pickupdatatypes}ShipmentDetails" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PickupType" type="{http://www.dhl.com/pickupdatatypes}PickupType" minOccurs="0"/>
 *         &lt;element name="LargestPiece" type="{http://www.dhl.com/pickupdatatypes}LargestPiece" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent> 
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "requestor",
    "place",
    "pickup",
    "pickupContact",
    "shipmentDetails",
    "pickupType",
    "largestPiece"
})
@XmlRootElement(name = "BookPickupRequest", namespace = "http://www.dhl.com")
public class BookPickupRequest {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "Requestor", required = true)
    protected Requestor requestor;
    @XmlElement(name = "Place", required = true)
    protected PlacePickup place;
    @XmlElement(name = "Pickup", required = true)
    protected Pickup pickup;
    @XmlElement(name = "PickupContact", required = true)
    protected ContactPickup pickupContact;
    @XmlElement(name = "ShipmentDetails")
    protected List<ShipmentDetailsPickup> shipmentDetails;
    @XmlElement(name = "PickupType")
    protected PickupType pickupType;
    @XmlElement(name = "LargestPiece")
    protected LargestPiece largestPiece;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link Requestor }
     *     
     */
    public Requestor getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Requestor }
     *     
     */
    public void setRequestor(Requestor value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link PlacePickup }
     *     
     */
    public PlacePickup getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacePickup }
     *     
     */
    public void setPlace(PlacePickup value) {
        this.place = value;
    }

    /**
     * Gets the value of the pickup property.
     * 
     * @return
     *     possible object is
     *     {@link Pickup }
     *     
     */
    public Pickup getPickup() {
        return pickup;
    }

    /**
     * Sets the value of the pickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pickup }
     *     
     */
    public void setPickup(Pickup value) {
        this.pickup = value;
    }

    /**
     * Gets the value of the pickupContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPickup }
     *     
     */
    public ContactPickup getPickupContact() {
        return pickupContact;
    }

    /**
     * Sets the value of the pickupContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPickup }
     *     
     */
    public void setPickupContact(ContactPickup value) {
        this.pickupContact = value;
    }

    /**
     * Gets the value of the shipmentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipmentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipmentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShipmentDetailsPickup }
     * 
     * 
     */
    public List<ShipmentDetailsPickup> getShipmentDetails() {
        if (shipmentDetails == null) {
            shipmentDetails = new ArrayList<ShipmentDetailsPickup>();
        }
        return this.shipmentDetails;
    }

    /**
     * Gets the value of the pickupType property.
     * 
     * @return
     *     possible object is
     *     {@link PickupType }
     *     
     */
    public PickupType getPickupType() {
        return pickupType;
    }

    /**
     * Sets the value of the pickupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupType }
     *     
     */
    public void setPickupType(PickupType value) {
        this.pickupType = value;
    }

    /**
     * Gets the value of the largestPiece property.
     * 
     * @return
     *     possible object is
     *     {@link LargestPiece }
     *     
     */
    public LargestPiece getLargestPiece() {
        return largestPiece;
    }

    /**
     * Sets the value of the largestPiece property.
     * 
     * @param value
     *     allowed object is
     *     {@link LargestPiece }
     *     
     */
    public void setLargestPiece(LargestPiece value) {
        this.largestPiece = value;
    }

}
