//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.01 at 06:34:59 PM EST 
//


package com.meritconinc.shiplinx.carrier.dhl.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Response" type="{http://www.dhl.com/datatypes}Response"/>
 *         &lt;element name="Note" type="{http://www.dhl.com/datatypes}Note"/>
 *         &lt;element name="ConfirmationNumber">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="999999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ReadyByTime" type="{http://www.dhl.com/pickupdatatypes}TimeHM" minOccurs="0"/>
 *         &lt;element name="SecondReadyByTime" type="{http://www.dhl.com/pickupdatatypes}TimeHM" minOccurs="0"/>
 *         &lt;element name="NextPickupDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PickupCharge" type="{http://www.dhl.com/datatypes}Money" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{http://www.dhl.com/datatypes}CurrencyCode" minOccurs="0"/>
 *         &lt;element name="CallInTime" type="{http://www.dhl.com/pickupdatatypes}TimeHM" minOccurs="0"/>
 *         &lt;element name="SecondCallInTime" type="{http://www.dhl.com/pickupdatatypes}TimeHM" minOccurs="0"/>
 *         &lt;element name="OriginSvcArea" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="3"/>
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CountryCode" type="{http://www.dhl.com/datatypes}CountryCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "note",
    "confirmationNumber",
    "readyByTime",
    "secondReadyByTime",
    "nextPickupDate",
    "pickupCharge",
    "currencyCode",
    "callInTime",
    "secondCallInTime",
    "originSvcArea",
    "countryCode"
})
@XmlRootElement(name = "PickupResponse", namespace = "http://www.dhl.com")
public class PickupResponse {

    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElement(name = "Note", required = true)
    protected Note note;
    @XmlElement(name = "ConfirmationNumber")
    protected int confirmationNumber;
    @XmlElement(name = "ReadyByTime")
    protected String readyByTime;
    @XmlElement(name = "SecondReadyByTime")
    protected String secondReadyByTime;
    @XmlElement(name = "NextPickupDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nextPickupDate;
    @XmlElement(name = "PickupCharge")
    protected Float pickupCharge;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "CallInTime")
    protected String callInTime;
    @XmlElement(name = "SecondCallInTime")
    protected String secondCallInTime;
    @XmlElement(name = "OriginSvcArea")
    protected String originSvcArea;
    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Note }
     *     
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Note }
     *     
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the confirmationNumber property.
     * 
     */
    public int getConfirmationNumber() {
        return confirmationNumber;
    }

    /**
     * Sets the value of the confirmationNumber property.
     * 
     */
    public void setConfirmationNumber(int value) {
        this.confirmationNumber = value;
    }

    /**
     * Gets the value of the readyByTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadyByTime() {
        return readyByTime;
    }

    /**
     * Sets the value of the readyByTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadyByTime(String value) {
        this.readyByTime = value;
    }

    /**
     * Gets the value of the secondReadyByTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondReadyByTime() {
        return secondReadyByTime;
    }

    /**
     * Sets the value of the secondReadyByTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondReadyByTime(String value) {
        this.secondReadyByTime = value;
    }

    /**
     * Gets the value of the nextPickupDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextPickupDate() {
        return nextPickupDate;
    }

    /**
     * Sets the value of the nextPickupDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextPickupDate(XMLGregorianCalendar value) {
        this.nextPickupDate = value;
    }

    /**
     * Gets the value of the pickupCharge property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPickupCharge() {
        return pickupCharge;
    }

    /**
     * Sets the value of the pickupCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPickupCharge(Float value) {
        this.pickupCharge = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the callInTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallInTime() {
        return callInTime;
    }

    /**
     * Sets the value of the callInTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallInTime(String value) {
        this.callInTime = value;
    }

    /**
     * Gets the value of the secondCallInTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondCallInTime() {
        return secondCallInTime;
    }

    /**
     * Sets the value of the secondCallInTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondCallInTime(String value) {
        this.secondCallInTime = value;
    }

    /**
     * Gets the value of the originSvcArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginSvcArea() {
        return originSvcArea;
    }

    /**
     * Sets the value of the originSvcArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginSvcArea(String value) {
        this.originSvcArea = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

}
