//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.01 at 06:34:59 PM EST 
//


package com.meritconinc.shiplinx.carrier.dhl.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Requestor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Requestor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="D"/>
 *               &lt;enumeration value="C"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccountNumber" type="{http://www.dhl.com/datatypes}AccountNumber" minOccurs="0"/>
 *         &lt;element name="ChargeCard" type="{http://www.dhl.com/pickupdatatypes}ChargeCard" minOccurs="0"/>
 *         &lt;element name="RequestorContact" type="{http://www.dhl.com/pickupdatatypes}RequestorContact" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Requestor", namespace = "http://www.dhl.com/pickupdatatypes", propOrder = {
    "accountType",
    "accountNumber",
    "chargeCard",
    "requestorContact"
})
public class Requestor {

    @XmlElement(name = "AccountType", required = true)
    protected String accountType;
    @XmlElement(name = "AccountNumber")
    protected Long accountNumber;
    @XmlElement(name = "ChargeCard")
    protected ChargeCardPickup chargeCard;
    @XmlElement(name = "RequestorContact")
    protected RequestorContact requestorContact;

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountNumber(Long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the chargeCard property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeCardPickup }
     *     
     */
    public ChargeCardPickup getChargeCard() {
        return chargeCard;
    }

    /**
     * Sets the value of the chargeCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeCardPickup }
     *     
     */
    public void setChargeCard(ChargeCardPickup value) {
        this.chargeCard = value;
    }

    /**
     * Gets the value of the requestorContact property.
     * 
     * @return
     *     possible object is
     *     {@link RequestorContact }
     *     
     */
    public RequestorContact getRequestorContact() {
        return requestorContact;
    }

    /**
     * Sets the value of the requestorContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestorContact }
     *     
     */
    public void setRequestorContact(RequestorContact value) {
        this.requestorContact = value;
    }

}
