
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-11T21:55:33.652-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "RateInq",
                      portName = "RateInqSoap",
                      targetNamespace = "http://tempuri.org/RATEINQ/Service1",
                      wsdlLocation = "RateInq.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.RateInqSoap")
                      
public class RateInqSoapImpl implements RateInqSoap {

    private static final Logger LOG = Logger.getLogger(RateInqSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.RateInqSoap#rateInq(java.lang.String  loginName ,)java.lang.String  password ,)java.lang.String  shipperAccountNumber ,)java.lang.String  fromPostalCode ,)java.lang.String  toPostalCode ,)java.lang.String  toCity ,)java.lang.String  toProvinceCode ,)java.lang.String  toCountryCode ,)java.lang.String  serviceType ,)javax.xml.datatype.XMLGregorianCalendar  pickupDate ,)java.lang.String  uom ,)com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.ArrayOfPiece  pieces ,)double  valuationAmount ,)boolean  isNonPack ,)boolean  isDangerousGood ,)boolean  isSaturdayDelivery ,)boolean  isFragile ,)boolean  isResidential ,)boolean  isDutiable ,)boolean  isDTP ,)java.lang.String  language )*
     */
    public com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.ReturnRates rateInq(java.lang.String loginName,java.lang.String password,java.lang.String shipperAccountNumber,java.lang.String fromPostalCode,java.lang.String toPostalCode,java.lang.String toCity,java.lang.String toProvinceCode,java.lang.String toCountryCode,java.lang.String serviceType,javax.xml.datatype.XMLGregorianCalendar pickupDate,java.lang.String uom,com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.ArrayOfPiece pieces,double valuationAmount,boolean isNonPack,boolean isDangerousGood,boolean isSaturdayDelivery,boolean isFragile,boolean isResidential,boolean isDutiable,boolean isDTP,java.lang.String language) { 
        LOG.info("Executing operation rateInq");
        System.out.println(loginName);
        System.out.println(password);
        System.out.println(shipperAccountNumber);
        System.out.println(fromPostalCode);
        System.out.println(toPostalCode);
        System.out.println(toCity);
        System.out.println(toProvinceCode);
        System.out.println(toCountryCode);
        System.out.println(serviceType);
        System.out.println(pickupDate);
        System.out.println(uom);
        System.out.println(pieces);
        System.out.println(valuationAmount);
        System.out.println(isNonPack);
        System.out.println(isDangerousGood);
        System.out.println(isSaturdayDelivery);
        System.out.println(isFragile);
        System.out.println(isResidential);
        System.out.println(isDutiable);
        System.out.println(isDTP);
        System.out.println(language);
        try {
            com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.ReturnRates _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
