
package com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-11T21:55:33.628-05:00
 * Generated source version: 2.5.0
 * 
 */
public final class RateInqHttpGet_RateInqHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/RATEINQ/Service1", "RateInq");

    private RateInqHttpGet_RateInqHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RateInq_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RateInq_Service ss = new RateInq_Service(wsdlURL, SERVICE_NAME);
        RateInqHttpGet port = ss.getRateInqHttpGet();  
        

        System.exit(0);
    }

}
