
package com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-11T21:55:33.702-05:00
 * Generated source version: 2.5.0
 * 
 */
 
public class RateInqHttpPost_RateInqHttpPost_Server{

    protected RateInqHttpPost_RateInqHttpPost_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new RateInqHttpPostImpl();
        String address = "http://canadacert.dhl.com/rateinq/RateInq.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new RateInqHttpPost_RateInqHttpPost_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
