package com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2012-02-11T21:55:33.680-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/RATEINQ/Service1", name = "RateInqSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface RateInqSoap {

    /**
     * To calculate rate
     */
    @WebResult(name = "RateInqResult", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
    @RequestWrapper(localName = "RateInq", targetNamespace = "http://tempuri.org/RATEINQ/Service1", className = "com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.RateInq")
    @WebMethod(operationName = "RateInq", action = "http://tempuri.org/RATEINQ/Service1/RateInq")
    @ResponseWrapper(localName = "RateInqResponse", targetNamespace = "http://tempuri.org/RATEINQ/Service1", className = "com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.RateInqResponse")
    public com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.ReturnRates rateInq(
        @WebParam(name = "LoginName", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String loginName,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String password,
        @WebParam(name = "ShipperAccountNumber", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String shipperAccountNumber,
        @WebParam(name = "FromPostalCode", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String fromPostalCode,
        @WebParam(name = "ToPostalCode", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String toPostalCode,
        @WebParam(name = "ToCity", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String toCity,
        @WebParam(name = "ToProvinceCode", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String toProvinceCode,
        @WebParam(name = "ToCountryCode", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String toCountryCode,
        @WebParam(name = "ServiceType", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String serviceType,
        @WebParam(name = "PickupDate", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        javax.xml.datatype.XMLGregorianCalendar pickupDate,
        @WebParam(name = "UOM", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String uom,
        @WebParam(name = "Pieces", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        com.meritconinc.shiplinx.carrier.loomis.ws.rateinq.proxy.ArrayOfPiece pieces,
        @WebParam(name = "ValuationAmount", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        double valuationAmount,
        @WebParam(name = "IsNonPack", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isNonPack,
        @WebParam(name = "IsDangerousGood", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isDangerousGood,
        @WebParam(name = "IsSaturdayDelivery", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isSaturdayDelivery,
        @WebParam(name = "IsFragile", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isFragile,
        @WebParam(name = "IsResidential", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isResidential,
        @WebParam(name = "IsDutiable", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isDutiable,
        @WebParam(name = "IsDTP", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        boolean isDTP,
        @WebParam(name = "Language", targetNamespace = "http://tempuri.org/RATEINQ/Service1")
        java.lang.String language
    );
}
