
package com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:50:30.760-04:00
 * Generated source version: 2.5.2
 * 
 */
 
public class ShippingServiceContract_ShippingServiceEndpoint_Server{

    protected ShippingServiceContract_ShippingServiceEndpoint_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ShippingServiceContractImpl();
        String address = "https://webservices.purolator.com/EWS/V1/Shipping/ShippingService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ShippingServiceContract_ShippingServiceEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
