
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-07-13T18:50:30.736-04:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "ShippingService",
                      portName = "ShippingServiceEndpoint",
                      targetNamespace = "http://purolator.com/pws/service/v1",
                      wsdlLocation = "ShippingService.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ShippingServiceContract")
                      
public class ShippingServiceContractImpl implements ShippingServiceContract {

    private static final Logger LOG = Logger.getLogger(ShippingServiceContractImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ShippingServiceContract#validateShipment(com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ValidateShipmentRequestContainer  validateShipmentRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ValidateShipmentResponseContainer validateShipment(ValidateShipmentRequestContainer validateShipmentRequest) throws ShippingServiceContractValidateShipmentValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation validateShipment");
        System.out.println(validateShipmentRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ValidateShipmentResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShippingServiceContractValidateShipmentValidationFaultFaultFaultMessage("ShippingServiceContract_ValidateShipment_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ShippingServiceContract#voidShipment(com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.VoidShipmentRequestContainer  voidShipmentRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.VoidShipmentResponseContainer voidShipment(VoidShipmentRequestContainer voidShipmentRequest) throws ShippingServiceContractVoidShipmentValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation voidShipment");
        System.out.println(voidShipmentRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.VoidShipmentResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShippingServiceContractVoidShipmentValidationFaultFaultFaultMessage("ShippingServiceContract_VoidShipment_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ShippingServiceContract#consolidate(com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ConsolidateRequestContainer  consolidateRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ConsolidateResponseContainer consolidate(ConsolidateRequestContainer consolidateRequest) throws ShippingServiceContractConsolidateValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation consolidate");
        System.out.println(consolidateRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ConsolidateResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShippingServiceContractConsolidateValidationFaultFaultFaultMessage("ShippingServiceContract_Consolidate_ValidationFaultFault_FaultMessage...");
    }

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.ShippingServiceContract#createShipment(com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.CreateShipmentRequestContainer  createShipmentRequest )*
     */
    public com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.CreateShipmentResponseContainer createShipment(CreateShipmentRequestContainer createShipmentRequest) throws ShippingServiceContractCreateShipmentValidationFaultFaultFaultMessage    { 
        LOG.info("Executing operation createShipment");
        System.out.println(createShipmentRequest);
        try {
            com.meritconinc.shiplinx.carrier.purolator.ws.shipping.proxy.CreateShipmentResponseContainer _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ShippingServiceContractCreateShipmentValidationFaultFaultFaultMessage("ShippingServiceContract_CreateShipment_ValidationFaultFault_FaultMessage...");
    }

}
