//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.21 at 10:03:06 PM EDT 
//


package com.meritconinc.shiplinx.ws.proxy.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
 

/**
 * <p>Java class for CustomsInvoiceWSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomsInvoiceWSType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BillTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillToAccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillToAddress" type="{http://www.proxy.ws.shiplinx.meritconinc.com/datatypes}AddressWSType"/>
 *         &lt;element name="Reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TotalValue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="TotalWeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TaxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrokerAddress" type="{http://www.proxy.ws.shiplinx.meritconinc.com/datatypes}AddressWSType"/>
 *         &lt;element name="Products" type="{http://www.proxy.ws.shiplinx.meritconinc.com/datatypes}CustomsInvoiceProductWSType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetaData" type="{http://www.proxy.ws.shiplinx.meritconinc.com/datatypes}MetaDataWSType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomsInvoiceWSType", propOrder = {
    "billTo",
    "billToAccountNum",
    "billToAddress",
    "reference",
    "currency",
    "totalValue",
    "totalWeight",
    "taxId",
    "brokerAddress",
    "products",
    "metaData"
})
public class CustomsInvoiceWSType {

    @XmlElement(name = "BillTo", required = true)
    protected String billTo;
    @XmlElement(name = "BillToAccountNum", required = true)
    protected String billToAccountNum;
    @XmlElement(name = "BillToAddress", required = true)
    protected AddressWSType billToAddress;
    @XmlElement(name = "Reference", required = true)
    protected String reference;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "TotalValue")
    protected double totalValue;
    @XmlElement(name = "TotalWeight")
    protected int totalWeight;
    @XmlElement(name = "TaxId", required = true)
    protected String taxId;
    @XmlElement(name = "BrokerAddress", required = true)
    protected AddressWSType brokerAddress;
    @XmlElement(name = "Products")
    protected List<CustomsInvoiceProductWSType> products;
    @XmlElement(name = "MetaData")
    protected List<MetaDataWSType> metaData;

    /**
     * Gets the value of the billTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTo() {
        return billTo;
    }

    /**
     * Sets the value of the billTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTo(String value) {
        this.billTo = value;
    }

    /**
     * Gets the value of the billToAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToAccountNum() {
        return billToAccountNum;
    }

    /**
     * Sets the value of the billToAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToAccountNum(String value) {
        this.billToAccountNum = value;
    }

    /**
     * Gets the value of the billToAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressWSType }
     *     
     */
    public AddressWSType getBillToAddress() {
        return billToAddress;
    }

    /**
     * Sets the value of the billToAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressWSType }
     *     
     */
    public void setBillToAddress(AddressWSType value) {
        this.billToAddress = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the totalValue property.
     * 
     */
    public double getTotalValue() {
        return totalValue;
    }

    /**
     * Sets the value of the totalValue property.
     * 
     */
    public void setTotalValue(double value) {
        this.totalValue = value;
    }

    /**
     * Gets the value of the totalWeight property.
     * 
     */
    public int getTotalWeight() {
        return totalWeight;
    }

    /**
     * Sets the value of the totalWeight property.
     * 
     */
    public void setTotalWeight(int value) {
        this.totalWeight = value;
    }

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxId(String value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the brokerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressWSType }
     *     
     */
    public AddressWSType getBrokerAddress() {
        return brokerAddress;
    }

    /**
     * Sets the value of the brokerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressWSType }
     *     
     */
    public void setBrokerAddress(AddressWSType value) {
        this.brokerAddress = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the products property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProducts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomsInvoiceProductWSType }
     * 
     * 
     */
    public List<CustomsInvoiceProductWSType> getProducts() {
        if (products == null) {
            products = new ArrayList<CustomsInvoiceProductWSType>();
        }
        return this.products;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metaData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetaDataWSType }
     * 
     * 
     */
    public List<MetaDataWSType> getMetaData() {
        if (metaData == null) {
            metaData = new ArrayList<MetaDataWSType>();
        }
        return this.metaData;
    }

}
