
package com.meritconinc.shiplinx.ws.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-04-29T13:56:13.680-04:00
 * Generated source version: 2.5.2
 */

@WebFault(name = "ShippingErrors", targetNamespace = "http://www.proxy.ws.shiplinx.meritconinc.com/datatypes")
public class ShippingException extends Exception {
    
    private com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType shippingErrors;

    public ShippingException() {
        super();
    }
    
    public ShippingException(String message) {
        super(message);
    }
    
    public ShippingException(String message, Throwable cause) {
        super(message, cause);
    }

    public ShippingException(String message, com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType shippingErrors) {
        super(message);
        this.shippingErrors = shippingErrors;
    }

    public ShippingException(String message, com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType shippingErrors, Throwable cause) {
        super(message, cause);
        this.shippingErrors = shippingErrors;
    }

    public com.meritconinc.shiplinx.ws.proxy.datatypes.ErrorsWSType getFaultInfo() {
        return this.shippingErrors;
    }
}
