
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.track.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T22:13:47.849-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "TrackService",
                      portName = "TrackPort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Track/v2.0",
                      wsdlLocation = "Track.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.track.proxy.TrackPortType")
                      
public class TrackPortTypeImpl implements TrackPortType {

    private static final Logger LOG = Logger.getLogger(TrackPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.track.proxy.TrackPortType#processTrack(com.meritconinc.shiplinx.carrier.ups.ws.track.proxy.TrackRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.track.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.track.proxy.TrackResponse processTrack(TrackRequest body,UPSSecurity upsSecurity) throws TrackErrorMessage    { 
        LOG.info("Executing operation processTrack");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.track.proxy.TrackResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TrackErrorMessage("TrackErrorMessage...");
    }

}
