package com.meritconinc.shiplinx.carrier.ups.ws.track.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-08T22:13:47.865-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Track/v2.0", name = "TrackPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TrackPortType {

    @WebResult(name = "TrackResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0", partName = "Body")
    @WebMethod(operationName = "ProcessTrack", action = "http://onlinetools.ups.com/webservices/TrackBinding/v2.0")
    public TrackResponse processTrack(
        @WebParam(partName = "Body", name = "TrackRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Track/v2.0")
        TrackRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws TrackErrorMessage;
}
