
package com.meritconinc.shiplinx.carrier.ups.ws.ratews.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T07:51:11.431-05:00
 * Generated source version: 2.5.0
 * 
 */
public final class RatePortType_RatePort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ups.com/WSDL/XOLTWS/Rate/v1.1", "RateService");

    private RatePortType_RatePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RateService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RateService ss = new RateService(wsdlURL, SERVICE_NAME);
        RatePortType port = ss.getRatePort();  
        
        {
        System.out.println("Invoking processRate...");
        com.meritconinc.shiplinx.carrier.ups.ws.ratews.proxy.RateRequest _processRate_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.ratews.proxy.UPSSecurity _processRate_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.ratews.proxy.RateResponse _processRate__return = port.processRate(_processRate_body, _processRate_upsSecurity);
            System.out.println("processRate.result=" + _processRate__return);

        } catch (RateErrorMessage e) { 
            System.out.println("Expected exception: RateErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
