package com.meritconinc.shiplinx.carrier.ups.ws.ratews.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T07:51:11.486-05:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.ups.com/WSDL/XOLTWS/Rate/v1.1", name = "RatePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RatePortType {

    @WebResult(name = "RateResponse", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1", partName = "Body")
    @WebMethod(operationName = "ProcessRate", action = "http://onlinetools.ups.com/webservices/RateBinding/v1.1")
    public RateResponse processRate(
        @WebParam(partName = "Body", name = "RateRequest", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/Rate/v1.1")
        RateRequest body,
        @WebParam(partName = "UPSSecurity", name = "UPSSecurity", targetNamespace = "http://www.ups.com/XMLSchema/XOLTWS/UPSS/v1.0", header = true)
        UPSSecurity upsSecurity
    ) throws RateErrorMessage;
}
