package com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.service.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.datatypes.v1.GetEstimateRequestContainer;
import com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.datatypes.v1.GetEstimateResponseContainer;


/**
 * Service Contract Class - FreightEstimatingServiceContract
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 *
 */
@WebService(name = "FreightEstimatingServiceContract", targetNamespace = "http://purolator.com/pws/service/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.org.datacontract.schemas._2004._07.microsoft_practices_enterpriselibrary_validation_integration.ObjectFactory.class,
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.datatypes.v1.ObjectFactory.class,
 com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.microsoft.practices.enterpriselibrary._2007._01.wcf.validation.ObjectFactory.class
})
public interface FreightEstimatingServiceContract {


 /**
 * GetEstimate
 * @param request GetEstimateRequest
 * @return GetEstimateResponse
 *
 * @param freightGetEstimateRequest
 * @return
 * returns com.purolator.pws.datatypes.v1.GetEstimateResponseContainer
 * @throws FreightEstimatingServiceContractGetEstimateValidationFaultFaultFaultMessage
 */
 @WebMethod(operationName = "GetEstimate", action = "http://purolator.com/pws/service/v1/Freight/GetEstimate")
 @WebResult(name = "GetEstimateResponse", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "GetEstimateResponse")
 public GetEstimateResponseContainer getEstimate(
 @WebParam(name = "FreightGetEstimateRequest", targetNamespace = "http://purolator.com/pws/datatypes/v1", partName = "FreightGetEstimateRequest")
 GetEstimateRequestContainer freightGetEstimateRequest)
 throws FreightEstimatingServiceContractGetEstimateValidationFaultFaultFaultMessage
 ;

}