package com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.service.v1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "FreightEstimatingService", targetNamespace = "http://purolator.com/pws/service/v1", wsdlLocation = "file:/media/hacker/Project2/project/soluship/Requirement/PurolatorFreight/LTL_Samples_WSDL/wsdl/FreightEstimating.wsdl")
public class FreightEstimatingService
 extends Service
{

 private final static URL FREIGHTESTIMATINGSERVICE_WSDL_LOCATION;
 private final static Logger logger = Logger.getLogger(com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.service.v1.FreightEstimatingService.class.getName());

 static {
 URL url = null;
 try {
 URL baseUrl;
 baseUrl = com.meritconinc.shiplinx.carrier.purolatorFreight.ws.estimating.com.purolator.pws.service.v1.FreightEstimatingService.class.getResource(".");
 url = new URL(baseUrl, "file:/media/hacker/Project2/project/soluship/Requirement/PurolatorFreight/LTL_Samples_WSDL/wsdl/FreightEstimating.wsdl");
 } catch (MalformedURLException e) {
 logger.warning("Failed to create URL for the wsdl Location: 'file:/media/hacker/Project2/project/soluship/Requirement/PurolatorFreight/LTL_Samples_WSDL/wsdl/FreightEstimating.wsdl', retrying as a local file");
 logger.warning(e.getMessage());
 }
 FREIGHTESTIMATINGSERVICE_WSDL_LOCATION = url;
 }

 public FreightEstimatingService(URL wsdlLocation, QName serviceName) {
 super(wsdlLocation, serviceName);
 }

 public FreightEstimatingService() {
 super(FREIGHTESTIMATINGSERVICE_WSDL_LOCATION, new QName("http://purolator.com/pws/service/v1", "FreightEstimatingService"));
 }

 /**
 *
 * @return
 * returns FreightEstimatingServiceContract
 */
 @WebEndpoint(name = "FreightEstimatingServiceEndpoint")
 public FreightEstimatingServiceContract getFreightEstimatingServiceEndpoint() {
 return super.getPort(new QName("http://purolator.com/pws/service/v1", "FreightEstimatingServiceEndpoint"), FreightEstimatingServiceContract.class);
 }

 /**
 *
 * @param features
 * A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the <code>features</code> parameter will have their default values.
 * @return
 * returns FreightEstimatingServiceContract
 */
 @WebEndpoint(name = "FreightEstimatingServiceEndpoint")
 public FreightEstimatingServiceContract getFreightEstimatingServiceEndpoint(WebServiceFeature... features) {
 return super.getPort(new QName("http://purolator.com/pws/service/v1", "FreightEstimatingServiceEndpoint"), FreightEstimatingServiceContract.class, features);
 }

}