
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T08:32:49.353-05:00
 * Generated source version: 2.5.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "TimeInTransitService",
                      portName = "TimeInTransitPort",
                      targetNamespace = "http://www.ups.com/WSDL/XOLTWS/TNT/v1.0",
                      wsdlLocation = "TNTWS.wsdl",
                      endpointInterface = "com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitPortType")
                      
public class TimeInTransitPortTypeImpl implements TimeInTransitPortType {

    private static final Logger LOG = Logger.getLogger(TimeInTransitPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitPortType#processTimeInTransit(com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitRequest  body ,)com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.UPSSecurity  upsSecurity )*
     */
    public com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitResponse processTimeInTransit(TimeInTransitRequest body,UPSSecurity upsSecurity) throws TimeInTransitErrorMessage    { 
        LOG.info("Executing operation processTimeInTransit");
        System.out.println(body);
        System.out.println(upsSecurity);
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new TimeInTransitErrorMessage("TimeInTransitErrorMessage...");
    }

}
