
package com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-10T08:32:49.314-05:00
 * Generated source version: 2.5.0
 * 
 */
public final class TimeInTransitPortType_TimeInTransitPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ups.com/WSDL/XOLTWS/TNT/v1.0", "TimeInTransitService");

    private TimeInTransitPortType_TimeInTransitPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TimeInTransitService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TimeInTransitService ss = new TimeInTransitService(wsdlURL, SERVICE_NAME);
        TimeInTransitPortType port = ss.getTimeInTransitPort();  
        
        {
        System.out.println("Invoking processTimeInTransit...");
        com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitRequest _processTimeInTransit_body = null;
        com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.UPSSecurity _processTimeInTransit_upsSecurity = null;
        try {
            com.meritconinc.shiplinx.carrier.ups.ws.tnt.proxy.TimeInTransitResponse _processTimeInTransit__return = port.processTimeInTransit(_processTimeInTransit_body, _processTimeInTransit_upsSecurity);
            System.out.println("processTimeInTransit.result=" + _processTimeInTransit__return);

        } catch (TimeInTransitErrorMessage e) { 
            System.out.println("Expected exception: TimeInTransitErrorMessage has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
